Contato.create!( nome: 'Major  Alexandre', email: 'tenalexandre@52ct.eb.mil.br', empresa_id: 7)
Contato.create!( nome: 'Capitão Ribamar', email: '', empresa_id: 7)
Contato.create!( nome: 'Arlindo Carlos Veras Filho', email: 'netline@netlinebr.com', empresa_id: 8)
Contato.create!( nome: 'Wilson Biancalana', email: 'infra@abctelecom.net.br', empresa_id: 9)
Contato.create!( nome: 'ANDRE MARTINS PEREIRA', email: 'TETANO123@HOTMAIL.COM', empresa_id: 10)
Contato.create!( nome: 'Alexandre Urbano', email: 'alexandre@adp3telecom.com', empresa_id: 11)
Contato.create!( nome: 'Rodrigo Bastos V. Teperino', email: 'rodrigoteperino@abin.gov.br', empresa_id: 12)
Contato.create!( nome: 'FABIANO COSTA DE ALMEIDA', email: 'fabiano.almeida@ana.gov.br', empresa_id: 13)
Contato.create!( nome: 'Daniel Wanderley Romão', email: 'danielromao@anatel.gov.br', empresa_id: 14)
Contato.create!( nome: 'João Procop', email: '', empresa_id: 15)
Contato.create!( nome: 'Wendel', email: '', empresa_id: 15)
Contato.create!( nome: 'Tiago Condé Pires Lopes', email: 'tiago.lopes@ancine.gov.br', empresa_id: 16)
Contato.create!( nome: 'Valmir Oliveira', email: 'vroliveira.ps@anp.gov.br', empresa_id: 17)
Contato.create!( nome: 'Gerson Pereira', email: 'gerson_pereira@hotmail.com', empresa_id: 18)
Contato.create!( nome: 'Giovanni Peres Russo', email: 'giovanni@akto.com.br', empresa_id: 19)
Contato.create!( nome: 'Rodrigo Longhi', email: 'rodrigo@sgnet-rs.com.br', empresa_id: 20)
Contato.create!( nome: 'Jean Assis Santos de Jesus', email: 'jean@alfatelecom.info', empresa_id: 21)
Contato.create!( nome: 'Jean Assis Santos de Jesus', email: 'atendimento@alfatelecom.info', empresa_id: 21)
Contato.create!( nome: 'Neuri Adriano Nobrega', email: 'nobrega@onlinevale.com.br', empresa_id: 22)
Contato.create!( nome: 'Antonio Sergio Silva Gomes', email: 'contato@virtualstar.com.br', empresa_id: 23)
Contato.create!( nome: 'José Sebastiao Moreira', email: 'info@alpinet.com.br', empresa_id: 24)
Contato.create!( nome: 'Andres Refatte Cheguhen', email: 'andres.arc@hotmail.com', empresa_id: 25)
Contato.create!( nome: 'Pablo Maurício de Castro', email: 'pabloapanet@gmail.com', empresa_id: 26)
Contato.create!( nome: 'Raphael Henrique Santos Silva', email: 'raphaelhss@gmail.com', empresa_id: 27)
Contato.create!( nome: 'Nelson Margarido', email: 'nelson.margarido@arionsolutions.com.br', empresa_id: 28)
Contato.create!( nome: 'Hebert Arrais Saraiva', email: 'maisnetprovedor@gmail.com', empresa_id: 29)
Contato.create!( nome: 'Cel. Marcelo Pacheco', email: 'agrsetorfin@gmail.com', empresa_id: 30)
Contato.create!( nome: 'Zuleika', email: 'zuleika@itep.br', empresa_id: 31)
Contato.create!( nome: 'César Henrique Kallas', email: 'cesarkallas@avancar.eng.br', empresa_id: 32)
Contato.create!( nome: 'Alaíne Silva Friedrich', email: 'alaine.internetka@hotmail.com', empresa_id: 33)
Contato.create!( nome: 'João Aprígio Nogueira Junior', email: 'joao@axtelecom.com.br', empresa_id: 34)
Contato.create!( nome: 'Fabricio Souza Horacio', email: 'horacio@axxess.com.br', empresa_id: 35)
Contato.create!( nome: 'Chaulk Blad Silva Balbino', email: 'chaulk6@hotmail.com', empresa_id: 36)
Contato.create!( nome: 'Manoel do E. Santos F. Souza', email: 'mannoelfranca@balsasnet.com.br', empresa_id: 37)
Contato.create!( nome: 'José Guilherme Barreto Ávila', email: 'guilherme.avila@bcb.gov.br', empresa_id: 38)
Contato.create!( nome: 'Kleber de Albuquerque Brasil', email: 'kleberbrasil@blznet.com', empresa_id: 39)
Contato.create!( nome: 'Clemildes Ferreira Martins', email: 'infotelatendimento@gmail.com', empresa_id: 40)
Contato.create!( nome: 'Bertone Martins', email: 'infotelatendimento@gmail.com', empresa_id: 40)
Contato.create!( nome: 'Antônio Olindo de Sousa Bomfim', email: 'bomfim_7@hotmail.com', empresa_id: 41)
Contato.create!( nome: 'Wendson da Silva Santos', email: 'netline@netlinebr.com', empresa_id: 42)
Contato.create!( nome: 'Wendson da Silva Santos', email: 'wendson.silva@netlinebr.com', empresa_id: 42)
Contato.create!( nome: 'Farilson S. Soares', email: 'farilson@bossnet.com.br', empresa_id: 43)
Contato.create!( nome: 'Tiago Matias dos Santos', email: 'tiagomatias@linuxap.com.br', empresa_id: 44)
Contato.create!( nome: 'Sandra Castro', email: 'scastro@brfibra.com.br', empresa_id: 45)
Contato.create!( nome: 'Marcello Sbardelini', email: 'ssbardelini@hotmail.com', empresa_id: 46)
Contato.create!( nome: 'Suely de Sousa Vera', email: 'brasilnetimperatriz@gmail.com', empresa_id: 47)
Contato.create!( nome: 'José Roberto Nogueira', email: 'roberto@brisanet.com.br', empresa_id: 48)
Contato.create!( nome: 'Luiz Bastian Junior', email: 'lbjunior@tcheturbo.com.br', empresa_id: 49)
Contato.create!( nome: 'Ismael Rech', email: 'ismael@brsulnet.com.br', empresa_id: 50)
Contato.create!( nome: 'Clezio Saraiva Tavares', email: 'contato@brtinformatica.com.br', empresa_id: 51)
Contato.create!( nome: 'Clezio Saraiva Tavares', email: 'clezio@brtinformatica.com.br', empresa_id: 51)
Contato.create!( nome: 'Edinaldo Ferreira do Amaral', email: 'edinaldo@byaltelecom.com.br', empresa_id: 52)
Contato.create!( nome: 'Edinaldo Ferreira do Amaral', email: 'edinaldo.amaral@hotmail.com', empresa_id: 52)
Contato.create!( nome: 'Nilmar da Silva Costa', email: 'nilmarcosta@hotmail.com', empresa_id: 53)
Contato.create!( nome: 'Paulo Henrique Martins Belga', email: 'cmsmartinsma@gmail.com', empresa_id: 54)
Contato.create!( nome: 'Claudio Pordeus Sarmento', email: 'claudiopordeussarmento@gmail.com', empresa_id: 55)
Contato.create!( nome: 'Claudio Pordeus Sarmento', email: 'claudiopordeussarmento@si', empresa_id: 55)
Contato.create!( nome: 'Creon Saraiva Tavares', email: 'creon@viponline.net.br', empresa_id: 56)
Contato.create!( nome: 'Wandson Francisco Cardoso Machado', email: 'wandson@linkwap.com.br', empresa_id: 57)
Contato.create!( nome: 'Jorge Abdon', email: 'jorge.abdon@caixa.gov.br', empresa_id: 58)
Contato.create!( nome: 'EDUARDO ANTONIO GLICÉRIO', email: 'eduardo@netsuper-es.com.br', empresa_id: 59)
Contato.create!( nome: 'Elizaldo Ribeiro Neves Santos', email: 'elizaldo@carolinaonline.com.br', empresa_id: 60)
Contato.create!( nome: 'Tenente Santana', email: 'santanajmps@aer.mil.br', empresa_id: 61)
Contato.create!( nome: 'Centro de Gerência de Rede - Engenharia', email: 'ativação@cemigtelecom.com', empresa_id: 62)
Contato.create!( nome: 'Centro de Gerência de Rede - Engenharia', email: 'coliveira@cemigtelecom.com', empresa_id: 62)
Contato.create!( nome: 'José Henrique Moraes Madeira', email: 'valdinea.leal@sipam.gov.br', empresa_id: 63)
Contato.create!( nome: 'Waleria Silva', email: 'waleria.silva@sipam.gov.br', empresa_id: 63)
Contato.create!( nome: 'Thiago Aquino Rosa de Oliveira', email: 'thiagoaquino@maxximatec.com.br', empresa_id: 64)
Contato.create!( nome: 'Renan L. Sausen', email: 'renan@ceriluz.com.br', empresa_id: 65)
Contato.create!( nome: 'Mateus', email: 'mateus@ceriluz.com.br', empresa_id: 65)
Contato.create!( nome: 'Gérson Barrey', email: 'gerson.barrey@procempa.com.br', empresa_id: 66)
Contato.create!( nome: 'Israel Arruda Neto', email: 'israelneto@fasternet.com.br', empresa_id: 67)
Contato.create!( nome: 'Capitão Max Silva ALALUNA', email: 'alaluna@citex.eb.mil.br', empresa_id: 68)
Contato.create!( nome: 'Erivelton Massen Gonçalves', email: 'erivelton@citydata.com.br', empresa_id: 69)
Contato.create!( nome: 'Almir Jose Salviano', email: 'clicknetbrasil@gmail.com', empresa_id: 70)
Contato.create!( nome: 'André Luiz Correia Filho Pelá', email: 'andreclinic@gmail.com', empresa_id: 71)
Contato.create!( nome: 'Ana Júlia Friedrich Marques', email: 'luiz.coelho@coelhotecnologia.com.br', empresa_id: 72)
Contato.create!( nome: 'Heitor de Oliveira', email: 'colinatel@gmail.com', empresa_id: 73)
Contato.create!( nome: 'Tenente Graice Kelly de Almeida', email: 'adj7.sg4@colog.eb.mil.br', empresa_id: 74)
Contato.create!( nome: 'Lindberg Ananias Filho', email: 'lindbergh@ciscea.gov.br', empresa_id: 75)
Contato.create!( nome: 'Capitão Carlos Renato Aguiar Brandão', email: 'brandao@41ct.eb.mil.br', empresa_id: 76)
Contato.create!( nome: 'Tenente Carlos Henrique da Cunha', email: 'cunha@4cta.eb.mil.br', empresa_id: 77)
Contato.create!( nome: 'Capitão Jorge Alves dos Santos Junior', email: 'alvesjunior@cdciber.eb.mil.br', empresa_id: 78)
Contato.create!( nome: 'Coronel Andrade', email: 'pggtic@solsi.eb.mil.br', empresa_id: 79)
Contato.create!( nome: 'Major Marco Aurélio', email: 'marcoaurelio@1cta.eb.mil.br', empresa_id: 80)
Contato.create!( nome: 'Marcio Ferreira Soares', email: 'contato@vitalnet.provedor.com.br', empresa_id: 81)
Contato.create!( nome: 'Regina Fatima da C. Siebra', email: 'regina.siebra@cprm.gov.br', empresa_id: 82)
Contato.create!( nome: 'Vitor César Martins Batista', email: 'batista730@hotmail.com', empresa_id: 83)
Contato.create!( nome: 'Marco Aurélio', email: 'financeiro@belvederecondominio.com.br', empresa_id: 84)
Contato.create!( nome: 'EDUARDO ANTONIO GLICÉRIO', email: 'uenderson@conectmais.com', empresa_id: 85)
Contato.create!( nome: 'Jovenil Rodrigues Abadia', email: 'bruno@sad.net.br', empresa_id: 86)
Contato.create!( nome: 'Warley', email: 'warley.viriato@caubr.gov.br', empresa_id: 87)
Contato.create!( nome: 'Rodrigo Colli', email: 'rodrigo.colli@corenmg.gov.br', empresa_id: 88)
Contato.create!( nome: 'Roberto Silva Morais', email: 'financeiro@coonexao.com', empresa_id: 89)
Contato.create!( nome: 'Marcos Bilhão', email: 'bilhao@copel.com', empresa_id: 90)
Contato.create!( nome: 'Narciso Aquino Flesch', email: 'nflesch@coprel.com.br', empresa_id: 91)
Contato.create!( nome: 'Cristiano Nunes', email: 'cristiano@turbonetssp.com.br', empresa_id: 92)
Contato.create!( nome: 'Marcelo Marra Assis', email: 'marcelo@conectlan.net.br', empresa_id: 93)
Contato.create!( nome: 'Karoline Castro Martins', email: '', empresa_id: 94)
Contato.create!( nome: 'Dailton de Oliveira Ferreira', email: 'grupoliderfinanceiro@gmail.com', empresa_id: 95)
Contato.create!( nome: 'Dailton de Oliveira Ferreira', email: 'dedinformatica@hotmail.com', empresa_id: 95)
Contato.create!( nome: 'Vanderson  Santana', email: 'vanderson@mobtelecom.com.br', empresa_id: 96)
Contato.create!( nome: 'Carlos André Giese', email: 'carlosg@dbserver.com.br', empresa_id: 97)
Contato.create!( nome: 'César Francisco de Almeida', email: 'cesar@vinet.com.br', empresa_id: 98)
Contato.create!( nome: 'Emerson Paulo Batista de Araújo', email: 'emerson.araujo@dbt.net.br', empresa_id: 99)
Contato.create!( nome: 'Lemuel da Silva Vieira', email: 'lemuel.vieira@prf.gov.br', empresa_id: 100)
Contato.create!( nome: 'Tenente Zonzini', email: 'rzonzini@gmail.com', empresa_id: 101)
Contato.create!( nome: 'Diego Hinz Soares', email: 'diegowillyne@gmail.com', empresa_id: 102)
Contato.create!( nome: 'Djean Oliveira Bezerra', email: 'makleysh@semfronteirasnet.com.br', empresa_id: 103)
Contato.create!( nome: 'ORION SOUZA', email: 'orionsouza@yahoo.com.br', empresa_id: 104)
Contato.create!( nome: 'Lopes Denis', email: 'lopes.denis@gmail.com', empresa_id: 104)
Contato.create!( nome: 'Silvio Macari ou Marco Macari', email: 'macari@dynatec.net.br', empresa_id: 105)
Contato.create!( nome: 'Ediney Marciano da Silva', email: 'ediney@garratelecom.com', empresa_id: 106)
Contato.create!( nome: 'Eber Dejani Pereira de Albernaz', email: 'ebersvp@hotmail.com', empresa_id: 107)
Contato.create!( nome: 'Flávio Roberto', email: 'flavio.antonio@eletronorte.gov.br', empresa_id: 108)
Contato.create!( nome: 'João Henrique da Silva', email: 'joao.henrique@eletrosul.gov.br', empresa_id: 109)
Contato.create!( nome: 'Emerson Weirich', email: 'emerson.weirich@ebc.com.br', empresa_id: 110)
Contato.create!( nome: 'Adriano Adoryan', email: '', empresa_id: 110)
Contato.create!( nome: 'Thiago Kovalski', email: 'tkovalski@correios.com.br', empresa_id: 111)
Contato.create!( nome: 'Raphael', email: 'raphael.mendes@hemobras.gov.br', empresa_id: 112)
Contato.create!( nome: 'ANTONIO GALLO', email: 'antonio@oletelecom.com.br', empresa_id: 113)
Contato.create!( nome: 'Theo Carlos Flexa Ribeiro Pires', email: 'theo.pires@prodepa.pa.gov.br', empresa_id: 114)
Contato.create!( nome: 'Maria Teresa Salek Dick Scorzelli', email: 'teresa.salek@dataprev.gov.br', empresa_id: 115)
Contato.create!( nome: 'Norton Pizzolatti', email: 'norton@engeplus.com.br', empresa_id: 116)
Contato.create!( nome: 'Vanderlei Boschetto', email: 'vanderlei@engetec.it', empresa_id: 117)
Contato.create!( nome: 'Anésio Arruda de Almeida', email: 'estreitonetsuporte@gmail.com', empresa_id: 118)
Contato.create!( nome: 'Capitão Weber José Neiva Chaves', email: 'tenweber@gabcmt.eb.mil.br', empresa_id: 119)
Contato.create!( nome: 'Capitão Danilo Fernandes Tenório', email: 'tenorio@7cta.eb.mil.br', empresa_id: 120)
Contato.create!( nome: 'Amilton De Lucca', email: 'alucca@enw.com.br', empresa_id: 121)
Contato.create!( nome: 'WALDER MIRANDA COSTA', email: 'waldermiranda@hotmail.com', empresa_id: 122)
Contato.create!( nome: 'WALDER MIRANDA COSTA', email: 'ultranet.pi@hotmail.com', empresa_id: 122)
Contato.create!( nome: 'Atil Gallarreta Faviero', email: 'atil@bnet.com.br', empresa_id: 123)
Contato.create!( nome: 'Frederico Barros', email: 'frederico@fazendomais.com.br', empresa_id: 124)
Contato.create!( nome: 'Fernando Fernandes de Melo', email: 'fernandonet33@gmail.com', empresa_id: 125)
Contato.create!( nome: 'Adriano Rodrigues', email: 'ed_damasceno@hotmail.com', empresa_id: 126)
Contato.create!( nome: 'Jose Fiuza da Cruz Junior', email: 'jrfiuza@gmail.com', empresa_id: 127)
Contato.create!( nome: 'Flavio Garcia Ferreira', email: 'flavio.cpa@caiaponia.net.br', empresa_id: 128)
Contato.create!( nome: 'José Flávio', email: 'financeiro.roo@inexa.com.br', empresa_id: 129)
Contato.create!( nome: 'Marcos Azevedo', email: 'marcos.azevedo@arenafontenova.com.br', empresa_id: 130)
Contato.create!( nome: 'FRANCISCA EDILEUZA MELO', email: 'os@edimelo.com.br', empresa_id: 131)
Contato.create!( nome: 'Aldejunior Pereira Barros', email: 'rteixeira@rteixeiratelecom.com.br', empresa_id: 132)
Contato.create!( nome: 'Raphael Augusto Pinto de Mattos', email: 'mattosraphael01@gmail.com', empresa_id: 133)
Contato.create!( nome: 'Marcia Martins Alves', email: '', empresa_id: 134)
Contato.create!( nome: 'Gilberto Santiago Araújo', email: 'gilbertosantiago@fiocruz.br', empresa_id: 135)
Contato.create!( nome: 'Mauro Agento', email: 'mauroag@furnas.com.br', empresa_id: 136)
Contato.create!( nome: 'Marcel Braga Furtado', email: 'interline.provedor@live.com', empresa_id: 137)
Contato.create!( nome: 'Rogério Fernandes de Souza', email: 'rogerio@g8.net.br', empresa_id: 138)
Contato.create!( nome: 'Janio Carvalho Pires', email: 'genesisinformaticajanio@hotmail.com', empresa_id: 139)
Contato.create!( nome: 'ADRIANO MOREIRA MIRANDA', email: 'adriano@gigabytenetwork.com.br', empresa_id: 140)
Contato.create!( nome: 'ADRIANO MOREIRA MIRANDA', email: 'kadash2006@gmail.com', empresa_id: 140)
Contato.create!( nome: 'Thiago Henrique Barros', email: 'thbarros@gmail.com', empresa_id: 141)
Contato.create!( nome: 'Thiago Mendes', email: '', empresa_id: 141)
Contato.create!( nome: 'Marcelo Figlarz', email: 'marcelo.figlarz@gvt.com.br', empresa_id: 142)
Contato.create!( nome: 'Geraldo Marcelo Nascimento Alves', email: 'comercial@microlinkinformatica.com', empresa_id: 143)
Contato.create!( nome: 'Genival Feitosa', email: 'jaksonribeiro@uol.com.br', empresa_id: 144)
Contato.create!( nome: 'Paulo de Tarso André Costa', email: 'tarso@gnex.com.br', empresa_id: 145)
Contato.create!( nome: 'Irineu Bayer', email: 'irineu.bayer@uol.com.br', empresa_id: 146)
Contato.create!( nome: 'Jean Santos Paes', email: 'jeanpaes@detic.ro.gov.br', empresa_id: 147)
Contato.create!( nome: 'Tenente Santana', email: 'santanajmps@aer.mil.br', empresa_id: 148)
Contato.create!( nome: 'ODILMAR CARLOS GAMA CUNHA', email: 'cunha@gconecta.com.br', empresa_id: 149)
Contato.create!( nome: 'Alex Raniere Oliveira de Souza', email: 'alex@portalgtnet.com.br', empresa_id: 150)
Contato.create!( nome: 'Sandro Gleidson de Oliveira Silva', email: 'sandro@gurisat.com.br', empresa_id: 151)
Contato.create!( nome: 'Eneas de Alcantara Silva', email: 'eneas.alcantara@ferroeste.com.br', empresa_id: 152)
Contato.create!( nome: 'Hugo Rodolfo Bohry Lacerda', email: 'hugo@redeconexaonet.com.br', empresa_id: 153)
Contato.create!( nome: 'GILVANDRO FERREIRA DA SILVA', email: 'halleytelecom@hotmail.com', empresa_id: 154)
Contato.create!( nome: 'Henrique Honório Pereira Cabral', email: 'shopnet@chuinet.com.br', empresa_id: 155)
Contato.create!( nome: 'Ernani Schmitt Tomedi', email: 'ernani@honos.com.br', empresa_id: 156)
Contato.create!( nome: 'João Vitor Teixeira', email: 'joaovitor.ict@gmail.com', empresa_id: 157)
Contato.create!( nome: 'Rodrigo Barroso Gonçalves', email: 'rodrigo@irtecnologia.com', empresa_id: 158)
Contato.create!( nome: 'Mario Sergio Moreira', email: 'i2telecomti@gmail.com', empresa_id: 159)
Contato.create!( nome: 'Rafael Diego Ferreira Araújo', email: 'rafaelmiliciaceleste@hotmail.com', empresa_id: 160)
Contato.create!( nome: 'Edgar Ribeiro de Abreu', email: 'edgar@iblnet.com.br', empresa_id: 161)
Contato.create!( nome: 'Euclydes Vieira Neto', email: 'euclydes@censanet.com.br', empresa_id: 162)
Contato.create!( nome: 'Euclydes Vieira Neto', email: 'euclydes@imatelecom.com.br', empresa_id: 162)
Contato.create!( nome: 'Reinaldo Silva Serra', email: 'gesup-imprensa@bol.com.br', empresa_id: 163)
Contato.create!( nome: 'Milton Ferreira da Silva', email: 'suporte@indnet.com.br', empresa_id: 164)
Contato.create!( nome: 'MARCO AURÉLIO SCHWVANTES', email: 'marco@infobarra.net.br', empresa_id: 165)
Contato.create!( nome: 'Marcelo Andrade Pimenta', email: 'marcelo.pimenta@ima.sp.gov.br', empresa_id: 166)
Contato.create!( nome: 'Mateus Bordini Rodrigues', email: 'redeinfosystem@gmail.com', empresa_id: 167)
Contato.create!( nome: 'Porfírio Holanda', email: 'pholanda@infraero.gov.br', empresa_id: 168)
Contato.create!( nome: 'Cosme Neto', email: 'cneto@inframerica.aero', empresa_id: 169)
Contato.create!( nome: 'Nelson Rezende', email: 'nelson.rezende@ibge.gov.br', empresa_id: 170)
Contato.create!( nome: 'Luiz Carlos Batista', email: 'luiz.batista@embratur.gov.br', empresa_id: 171)
Contato.create!( nome: 'Daniel de Souza Vasconcelos', email: 'Daniel.Vasconcelos@ibama.gov.br', empresa_id: 172)
Contato.create!( nome: 'Fabrício de Souza Duarte', email: 'fabricio.duarte@telebras.com.br', empresa_id: 173)
Contato.create!( nome: 'Éder Gillian', email: 'eder.beserra@ipea.gov.br', empresa_id: 175)
Contato.create!( nome: 'Anderson de Castro Lima', email: 'anclima@gmail.com', empresa_id: 176)
Contato.create!( nome: 'Vanderson Jeronimo Santana', email: 'vjsantana@timbrasil.com.br', empresa_id: 177)
Contato.create!( nome: 'Fernando Rosado Miron', email: 'grsales@grtelecom.com.br', empresa_id: 178)
Contato.create!( nome: 'Ricardo Ohara', email: 'rohara@internexa.com', empresa_id: 179)
Contato.create!( nome: 'Helder Simionato', email: 'helder_mt@hotmail.com', empresa_id: 180)
Contato.create!( nome: 'Jefferson Pereira De Carvalho', email: 'jeff@ipcarrier.us', empresa_id: 181)
Contato.create!( nome: 'Jefferson Pereira de Carvalho', email: 'jeff@ipcarrier.us', empresa_id: 182)
Contato.create!( nome: 'Adriano', email: 'adriano@ipinfo.com.br', empresa_id: 183)
Contato.create!( nome: 'Evandro Assis Costa Gonçalves', email: 'evandro.goncalves@isotelco.com.br', empresa_id: 184)
Contato.create!( nome: 'Jamyson Machado Gois', email: 'jmitnet@gmail.com', empresa_id: 185)
Contato.create!( nome: 'JULIO DA LUZ MORAES', email: 'megasoftmoraes@gmail.com', empresa_id: 186)
Contato.create!( nome: 'Júnior César Silva', email: 'juniorsilva@meganet.com.vc', empresa_id: 187)
Contato.create!( nome: 'Crispim Jacques', email: 'crispim105@hotmail.com', empresa_id: 188)
Contato.create!( nome: 'Crispim Jacques', email: 'manuelalmeida@hotmail.com', empresa_id: 188)
Contato.create!( nome: 'Crispim Jaques de Vasconcelos', email: 'crispim105@hotmail.com', empresa_id: 189)
Contato.create!( nome: 'Crispim Jaques de Vasconcelos', email: 'jlc@realonline.com.br', empresa_id: 189)
Contato.create!( nome: 'João José Alves Batista', email: 'joaojcortes@gmail.com', empresa_id: 190)
Contato.create!( nome: 'Pedro Fontela', email: 'pedro.fontela@gmail.com', empresa_id: 191)
Contato.create!( nome: 'Renato dos Santos Frazão', email: 'renatos2005@hotmail.com', empresa_id: 192)
Contato.create!( nome: 'Gilliardo Costa Sales', email: 'gilliardo@bol.com.br', empresa_id: 193)
Contato.create!( nome: 'Julio de Souza Franco Neto', email: 'infortread.am@gmail.com', empresa_id: 194)
Contato.create!( nome: 'Mauro Collatto', email: 'mauro.collatto@juntotelecom.com.br', empresa_id: 195)
Contato.create!( nome: 'Luciano Inácio Goçalves Lima', email: 'luciano@jupiter.com.br', empresa_id: 196)
Contato.create!( nome: 'Anailson Gomes Laranjeiras', email: 'eneas.alcantara@ferroeste.com.br', empresa_id: 197)
Contato.create!( nome: 'Ulisses', email: 'ulisses@nippontec.net', empresa_id: 198)
Contato.create!( nome: 'Alessandro Rodrigues Gaitkoski', email: 'gaitkoskinet@hotmail.com', empresa_id: 199)
Contato.create!( nome: 'Reinaldo Cavalvante', email: 'telecomregional@gmail.com', empresa_id: 200)
Contato.create!( nome: 'Larry de Carvalho', email: 'larrymsi@gmail.com', empresa_id: 201)
Contato.create!( nome: 'Luciano Vargas dos Santos', email: 'luciano@andrasta.com.br', empresa_id: 202)
Contato.create!( nome: 'Dener Machado Silva', email: 'lagosnetminas@lagosnetminas.com.br', empresa_id: 203)
Contato.create!( nome: 'Wilson Trinidad', email: 'interlans@gmail.com', empresa_id: 204)
Contato.create!( nome: 'Leonardo Gonçalves', email: 'leonardo.goncalves@gdc.net.br', empresa_id: 205)
Contato.create!( nome: 'Paulo Henrique de Araujo', email: 'paulohenrique@phnettelecom.com.br', empresa_id: 206)
Contato.create!( nome: 'Gil Alves de Oliveira', email: 'gilalvesadv@hotmail.com', empresa_id: 207)
Contato.create!( nome: 'Claudinei Menezes de Carvalho', email: 'atapinfo@gmail.com', empresa_id: 208)
Contato.create!( nome: 'EMILIANO REYES', email: 'emiliano.reyes@flin.com.br', empresa_id: 209)
Contato.create!( nome: 'Cassio Murilo Barcelos', email: 'cassio.barcelos@plenatrans.com.br', empresa_id: 210)
Contato.create!( nome: 'Andre Luiz Gonçalves', email: 'andre@logtel.net.br', empresa_id: 211)
Contato.create!( nome: 'Joao Eduardo  Carneiro Lucaroni', email: 'ceo@netmaispalmas.com.br', empresa_id: 212)
Contato.create!( nome: 'Douglas Estacio Sagmeister', email: 'ruraltecsvs@hotmail.com', empresa_id: 213)
Contato.create!( nome: 'Marcelo de Sousa Duarte', email: 'msdpalmas@hotmail.com', empresa_id: 214)
Contato.create!( nome: 'Everson Kleber Mai', email: 'everson@maisinternet.net.br', empresa_id: 215)
Contato.create!( nome: 'Larissa Ferreira', email: 'larissa.ferreira@mapminas.com.br', empresa_id: 216)
Contato.create!( nome: 'Marcio Meireles de Souza', email: 'martzinformatica@gmail.com', empresa_id: 217)
Contato.create!( nome: 'Daniel Lima Junqueira', email: 'suporte@masterdatanet.com.br', empresa_id: 218)
Contato.create!( nome: 'Fernando Sousa Gouveia', email: 'masteronlinescm@bol.com.br', empresa_id: 219)
Contato.create!( nome: 'Anderson Cláudio Amaral', email: 'maximidia@mxt.net.br', empresa_id: 220)
Contato.create!( nome: 'Jean de Souza Rocha', email: 'adm.rs@nabcdtem.com.br', empresa_id: 221)
Contato.create!( nome: 'Marcos Paulo da Silva Santos', email: 'diretoria@helpnews.com.br', empresa_id: 222)
Contato.create!( nome: 'Fábio Agrizzi Cipriano', email: 'fabio@mdconnect.com.br', empresa_id: 223)
Contato.create!( nome: 'Marcos Aurelio Cid Bendor', email: 'marcosbendor@gmail.com', empresa_id: 224)
Contato.create!( nome: 'LEONARDO VILLAR', email: 'leovillar@uol.com.br', empresa_id: 225)
Contato.create!( nome: 'Paulo Hernane Cardoso da Silva', email: 'financeiro@engetronics.com.br', empresa_id: 226)
Contato.create!( nome: 'Gilson Fernando Botta', email: 'gilson.botta@mcti.gov.br', empresa_id: 227)
Contato.create!( nome: 'Jonas Jeske', email: 'jonas.jeske@cultura.gov.br', empresa_id: 228)
Contato.create!( nome: 'Renato Viana', email: 'renato.viana@defesa.gov.br ', empresa_id: 229)
Contato.create!( nome: 'Carlos Maurício', email: 'carlos.mauricio@defesa.gov.br', empresa_id: 229)
Contato.create!( nome: 'Cláudio Augusto Novais Ferraz', email: 'claudio.ferraz@mdic.gov.br', empresa_id: 230)
Contato.create!( nome: 'Marcelo Nogueira Lino', email: 'marcelo.lino@mj.gov.br', empresa_id: 231)
Contato.create!( nome: 'Márcio R. de Paiva', email: 'marcio.paiva@saude.gov.br', empresa_id: 232)
Contato.create!( nome: 'Yuiti Oki Niyama', email: 'yuiti.niyama@cidades.gov.br', empresa_id: 233)
Contato.create!( nome: 'Alexandre Stecher', email: 'alexandre.stecher@mme.gov.br', empresa_id: 234)
Contato.create!( nome: 'Amaury', email: 'amaury.silveira@florestal.gov.br', empresa_id: 235)
Contato.create!( nome: 'Jaime Heleno Correa de Lisboa', email: 'jaime.lisboa@mma.gov.br', empresa_id: 236)
Contato.create!( nome: 'Silvio César da Silva Lima - Vinícius Alves', email: 'silvio.lima@planejamento.gov.br', empresa_id: 237)
Contato.create!( nome: 'Vinícius Alves', email: '', empresa_id: 237)
Contato.create!( nome: 'Davi Vernon', email: 'davi.vernon@mtb.gov.br', empresa_id: 238)
Contato.create!( nome: 'Cleiton Dias', email: 'cleiton.dias@mte.gov.br', empresa_id: 239)
Contato.create!( nome: 'Ramon David de Souza', email: ' ramon.souza@projetos.turismo', empresa_id: 240)
Contato.create!( nome: 'André Luiz Ferreira dos Santos', email: 'andre.santos@turismo.gov.br', empresa_id: 240)
Contato.create!( nome: 'Carlos', email: '', empresa_id: 241)
Contato.create!( nome: 'Pedro José dos Santos', email: 'pedro.santos@mpt.mp.br', empresa_id: 242)
Contato.create!( nome: 'Maurício Mello de Andrade', email: 'mauricio@andrade.eti.br', empresa_id: 243)
Contato.create!( nome: 'Maurício Mello de Andrade', email: 'mandrade@mma.com.br', empresa_id: 243)
Contato.create!( nome: 'Marcilio Ricardo da Costa Soares', email: 'suporte@multlink.net.br', empresa_id: 244)
Contato.create!( nome: 'Nielson Reis da Silva', email: 'www.fibernetwork.com.br', empresa_id: 245)
Contato.create!( nome: 'André Luiz N Lopes', email: 'nepomuceno@bol.com.br', empresa_id: 246)
Contato.create!( nome: 'Leocir Menegat', email: 'suporte@najatelecom.com.br', empresa_id: 247)
Contato.create!( nome: 'José Ribamar da Silva Barros', email: 'riba.barros@gmail.com', empresa_id: 248)
Contato.create!( nome: 'José Ribamar da Silva Barros', email: ' ribamar@neolog.net.br', empresa_id: 248)
Contato.create!( nome: 'Fernando Henrique', email: 'fernando@netbarretos.com.br', empresa_id: 249)
Contato.create!( nome: 'MARCOS SOARES DE SOUZA', email: 'naldoksa@hotmail.com', empresa_id: 250)
Contato.create!( nome: 'MARCOS SOARES DE SOUZA', email: 'soares@itrixti.com.br', empresa_id: 250)
Contato.create!( nome: 'Evandro Loiola de Amorim', email: 'nsevandro@gmail.com', empresa_id: 251)
Contato.create!( nome: 'Reginaldo Cardoso de Souza', email: 'reginaldo@netsulonline.com.br', empresa_id: 252)
Contato.create!( nome: 'Kleber Nascimento Ribeiro', email: 'kribeiro_netmaxi@hotmail.com', empresa_id: 253)
Contato.create!( nome: 'Neuber Modesto Fontoura', email: 'linkcomputadores@hotmail.com', empresa_id: 254)
Contato.create!( nome: 'Danilo Machado Silva', email: 'nippynet@hotmail.com', empresa_id: 255)
Contato.create!( nome: 'Carlos Eduardo Moreira', email: 'niqturbo@niqturbo.com.br', empresa_id: 256)
Contato.create!( nome: 'Alexandre Resende', email: 'alexandre.resende@noroestecom.com.br', empresa_id: 257)
Contato.create!( nome: 'Mauro Roberto Collato Junior', email: 'mrcj.sp@gmail.com', empresa_id: 258)
Contato.create!( nome: 'Sérgio Renato Silveira de Oliveira', email: 'sergio@v-expressa.com.br', empresa_id: 259)
Contato.create!( nome: 'Antônio Carlos Sabches', email: 'asanches@omini.net.br', empresa_id: 260)
Contato.create!( nome: 'Jose Eduardo Santos Paiva', email: 'eduardopaiva@cultura.com.br', empresa_id: 261)
Contato.create!( nome: 'Claudemon Silveira', email: 'claudemon@oops.net.br', empresa_id: 262)
Contato.create!( nome: 'VINICIOS LEITZKE', email: 'vinicios@osirnet.com.br', empresa_id: 263)
Contato.create!( nome: 'André Giachim', email: 'andre@p4telecom.com.br', empresa_id: 264)
Contato.create!( nome: 'Sergio Araujo', email: 'sergio.araujo@paim.com.br', empresa_id: 265)
Contato.create!( nome: 'Crispim Paiva Santana', email: 'eneas.alcantara@ferroeste.com.br', empresa_id: 266)
Contato.create!( nome: 'Paulo de Tarso de Carvalho Bayma Filho', email: 'paulo@wikitelecom.com.br', empresa_id: 267)
Contato.create!( nome: 'Paulo Cesar Silva', email: 'vpdsilva@hotmail.com', empresa_id: 268)
Contato.create!( nome: 'José Augusto de L Pinto Marques', email: 'augusto.marques@petrobras.com.br', empresa_id: 269)
Contato.create!( nome: 'Jose Maria dos Reis Cardoso', email: 'josemaria@hitsfiber.com.br', empresa_id: 270)
Contato.create!( nome: 'Marcondes Mainardi', email: 'marcondesmainardi@hotmail.com', empresa_id: 271)
Contato.create!( nome: 'Donizetti de Melo Matos', email: 'diretoria@polycanal.com.br', empresa_id: 272)
Contato.create!( nome: 'Manoel do E. Santos F. Souza', email: 'djfiguradj@hotmail.com', empresa_id: 273)
Contato.create!( nome: 'Josilene Gomes de Oliveira', email: 'josisg@yahoo.com.br', empresa_id: 274)
Contato.create!( nome: 'Filipe Conesuque Gurgel do Amaral', email: 'filipe@pvt.net.br', empresa_id: 275)
Contato.create!( nome: 'Guilherme Henrique de Ávila', email: 'samir.cti@barretos.sp.gov.br', empresa_id: 276)
Contato.create!( nome: 'Humberto Jorge Leitão de Brito', email: 'hjlbrito@yahoo.com.br', empresa_id: 277)
Contato.create!( nome: 'Jose Santana Neto', email: 'gab.prefeito@colinas.to.gov.br', empresa_id: 278)
Contato.create!( nome: 'Leonardo Cavalieri', email: 'leonrado.cavalieri@iplanrio.rio.rj.gov.br', empresa_id: 279)
Contato.create!( nome: 'Kleberson Maxmiller', email: 'santavitoriadopalmar@gmail.com', empresa_id: 280)
Contato.create!( nome: 'Mario Sérgio Moreira', email: 'mariosergio@anapolis.go.gov.br', empresa_id: 281)
Contato.create!( nome: 'Gustavo Luiz Alberto Maguito Villela', email: 'gustavo.30939@aparecida.go.gov.br', empresa_id: 282)
Contato.create!( nome: 'Endrigo Lucas Gambarato Bertin - Prefeito', email: 'pmcolombia1@netsite.com.br', empresa_id: 283)
Contato.create!( nome: 'Werther (Secretário de Saúde)', email: 'werther@pmlem.ba.gov.br', empresa_id: 284)
Contato.create!( nome: 'Humberto Menezes da Trindade', email: 'pmcpd01@yahoo.com.br', empresa_id: 285)
Contato.create!( nome: 'David Leite da Silva', email: '', empresa_id: 286)
Contato.create!( nome: 'George Lino Pompeu Wanzeler', email: 'pompeu500@yahoo.com.br', empresa_id: 287)
Contato.create!( nome: 'Marcelo Ferreira Pinheiro', email: 'marcelo.pinheiro@planalto.gov.br', empresa_id: 288)
Contato.create!( nome: 'Maurício Bittencourt', email: '', empresa_id: 288)
Contato.create!( nome: 'Robson Germano', email: ' robson.germano@presidenci', empresa_id: 288)
Contato.create!( nome: 'Romulo Medeiros Silva', email: 'atendimentoprime@hotmail.com', empresa_id: 289)
Contato.create!( nome: 'Romulo Medeiros Silva', email: 'ro-medeiros@hotmail.com', empresa_id: 289)
Contato.create!( nome: 'Flavio Arthur Leal Ferreira', email: 'arthur@procergs.rs.gov.br', empresa_id: 290)
Contato.create!( nome: 'Marcio Mota', email: 'marcio.mota@prodam.am.gov.br', empresa_id: 291)
Contato.create!( nome: 'Haroldo Cohen', email: 'haroldojr@prodam.am.gov.br', empresa_id: 291)
Contato.create!( nome: 'Leandro Conde Figueiras', email: 'leandro.conde@pronto.net.br', empresa_id: 292)
Contato.create!( nome: ' Eduardo Augusto Figueiredo Medeiros', email: 'eduardo@provecom.com.br', empresa_id: 293)
Contato.create!( nome: 'Raimundo Lima Guimaraes', email: 'mastersoftwere@hotmail.com', empresa_id: 294)
Contato.create!( nome: 'Rosivaldo Machado e Oliveira', email: 'alfawalker@gmail.com', empresa_id: 295)
Contato.create!( nome: 'Antônio Maurilio S. de Mesquita', email: 'maurilio@redenet.com.br', empresa_id: 296)
Contato.create!( nome: 'Marcos Monteiro- Robson Pinheiro', email: 'mmdsilva@band.com.br', empresa_id: 297)
Contato.create!( nome: 'Marcelo Pereira Martins', email: 'marcelo@radionettelecom.com', empresa_id: 298)
Contato.create!( nome: 'Robson Lustosa Ribeiro', email: 'financeiroacesso.com.df@gmail.com', empresa_id: 299)
Contato.create!( nome: 'Flávio Moraes', email: 'flavio@conesul.net', empresa_id: 300)
Contato.create!( nome: 'Alan Carneiro Pinheiro', email: 'alan@carajasnet.com', empresa_id: 301)
Contato.create!( nome: 'André W. S. Mesquita', email: 'andre@passosnet.com.br', empresa_id: 302)
Contato.create!( nome: 'Rodrigo Arantes', email: 'rarantes@tvglobo.com.br', empresa_id: 303)
Contato.create!( nome: 'Jadson Welder da Silva Melo', email: 'jadson@sivnet.com.br', empresa_id: 304)
Contato.create!( nome: 'Jadson Welder da Silva Melo', email: 'noc@sivnet.com.br', empresa_id: 304)
Contato.create!( nome: 'Walter Pereira Filho', email: 'walter@speednetma.com.br', empresa_id: 305)
Contato.create!( nome: 'Antônio Carlos Augusto', email: 'ac@reditel.net.br', empresa_id: 306)
Contato.create!( nome: 'Guilherme Freitas Castro', email: 'guilherme@acem.net.br', empresa_id: 307)
Contato.create!( nome: 'Ricardo Santos de Jesus', email: 'vivatelecom.mineiros@gmail.com', empresa_id: 308)
Contato.create!( nome: 'NOC-DF 24X7', email: 'noc@rnp.br', empresa_id: 309)
Contato.create!( nome: 'Rodrigo Castro Andrade', email: 'RCARODRIGO@HOTMAIL.COM', empresa_id: 310)
Contato.create!( nome: 'Rodrigo Costa Machado', email: 'rodrigo@digitelecom.jcom', empresa_id: 311)
Contato.create!( nome: 'Rodrigo José Marasca', email: 'rodrigo@primatecmt.com.br', empresa_id: 312)
Contato.create!( nome: 'Analberto Barbosa Rodrigues', email: 'analberto@imperanet.com.br', empresa_id: 313)
Contato.create!( nome: 'Wellington Pereira de Arruda', email: 'gerencia@rondonet-telecom.com.br', empresa_id: 314)
Contato.create!( nome: 'Raimundo Rubens Silva Lima', email: 'rubens@rondotech.com.br', empresa_id: 315)
Contato.create!( nome: 'Lauricio Possebon', email: 'lauricio@ruraltecrs.com.br', empresa_id: 316)
Contato.create!( nome: 'Luiz Carlos Zancanella', email: 'luizcarlos@safeweb.com.br', empresa_id: 317)
Contato.create!( nome: 'Manoel Pedro Da Conceição Filho', email: 'pedro@asatelecom.net', empresa_id: 318)
Contato.create!( nome: 'Santina Pereira Pinto Tavares', email: 'santina@megaturbo.net.br', empresa_id: 319)
Contato.create!( nome: 'Orivaldo das Neves Oliveira', email: 'orivaldo@nevolitelecom.com.br', empresa_id: 320)
Contato.create!( nome: 'Rogerio Araujo Soares', email: 'rede@helpinternet.com.br', empresa_id: 321)
Contato.create!( nome: 'Vitor Isaac Tannus Souza', email: 'vitor.souza@aviacaocivil.gov.br', empresa_id: 322)
Contato.create!( nome: 'Weldson Queiroz de Lima', email: 'weldson.lima@serpro.gov.br', empresa_id: 323)
Contato.create!( nome: 'Aline Barbosa', email: 'aline.barbosa@serpro.gov.br', empresa_id: 323)
Contato.create!( nome: 'Lauro Crispim de Sousa Jr', email: 'lauro.crispim@sebrae.com.br', empresa_id: 324)
Contato.create!( nome: 'Biramar', email: 'biramar@redemulticom.info', empresa_id: 325)
Contato.create!( nome: 'MAURICIO AIMI', email: 'briw_set@hotmail.com', empresa_id: 326)
Contato.create!( nome: 'MAURICIO AIMI', email: 'ione_50@hotmail.com', empresa_id: 326)
Contato.create!( nome: 'Júlio César Arraes Vieira Filho', email: 'gerencia@7con.com.br', empresa_id: 327)
Contato.create!( nome: 'Silmar Zamboni', email: 'jaguarinet@brturbo.com.br', empresa_id: 328)
Contato.create!( nome: 'Luiz Jocelmo', email: 'ciacom@ciacom.com.br', empresa_id: 329)
Contato.create!( nome: 'Suelismar Caetano Ferreira', email: 'suelismar@hotmail.com', empresa_id: 330)
Contato.create!( nome: 'Rogério Ferreira dos Santos', email: 'roger@simonet.com.br', empresa_id: 331)
Contato.create!( nome: 'Adriel Gonçalves Pereira', email: 'atendimento@sinal.net.br', empresa_id: 332)
Contato.create!( nome: 'LUIZ CARLOS ZAT', email: 'LUIZ.ZAT@SINERGY.COM.BR', empresa_id: 333)
Contato.create!( nome: 'Felix Gonçalves de Miranda-Gleuber', email: 'fmirandask@hotmail.com', empresa_id: 334)
Contato.create!( nome: 'Cesar Tozzi', email: 'Cesar.Tozzi@sky.com.br', empresa_id: 335)
Contato.create!( nome: ' Wander Monteiro', email: 'wander.monteiro@sky.com.br', empresa_id: 335)
Contato.create!( nome: 'Jumar Alves Pena', email: 'jumarsuportenet@hotmail.com', empresa_id: 336)
Contato.create!( nome: 'Rogério dos Santos', email: 'rogerio@webroute.com.br', empresa_id: 337)
Contato.create!( nome: 'Marília', email: 'marilia@riosoft.org.br', empresa_id: 338)
Contato.create!( nome: 'Silvano Junio Pereira', email: 'clicknet.tele@gmail.com', empresa_id: 339)
Contato.create!( nome: 'Moisés Ferreira da Silva', email: 'moyses@speedplanet.com.br', empresa_id: 340)
Contato.create!( nome: 'Eduardo Noleto de Freitas', email: 'eduardo@speedconnect.net.br', empresa_id: 341)
Contato.create!( nome: 'Marcus Vinicius', email: 'speednetpa@hotmail.com', empresa_id: 342)
Contato.create!( nome: 'Ermilson Costa da Silva', email: 'ermilson@contilnet.com.br', empresa_id: 343)
Contato.create!( nome: 'Edilson Borges de Freitas', email: 'edilson@viaradio.qsl.br', empresa_id: 344)
Contato.create!( nome: 'Antonio Jorge Amaral Lobato', email: 'jorge@stonetecnologia.com', empresa_id: 345)
Contato.create!( nome: 'Emerson Jose', email: 'dane.silva@vogeltelecom.com', empresa_id: 346)
Contato.create!( nome: 'Emerson Jose', email: 'emerson.magalhaes@vogeltelecom', empresa_id: 346)
Contato.create!( nome: 'Carlos Alberto da Silva Moraes', email: 'contato@coparpa.com.br', empresa_id: 347)
Contato.create!( nome: 'Carlos Antônio Ferreira', email: 'carlosradiom@gmail.com', empresa_id: 348)
Contato.create!( nome: 'Luiz Bastian Junior', email: 'lbjunior@tcheturbo.com.br', empresa_id: 349)
Contato.create!( nome: 'Edney Cabral Alarcão', email: 'edney@bycabral.com', empresa_id: 350)
Contato.create!( nome: 'Jose Augusto DinizRafael Nunes', email: 'augustodiniz@tvn.tv', empresa_id: 352)
Contato.create!( nome: 'Jose Augusto DinizRafael Nunes', email: 'brrafanun@tvn.tv.br', empresa_id: 352)
Contato.create!( nome: 'Leonardo Faustino De Souza Ribeiro', email: 'lfribeiro@timbrasil.com.br', empresa_id: 353)
Contato.create!( nome: 'Alexandro Andrade Toledo', email: 'alexandro@toledoinformatica.com.br', empresa_id: 354)
Contato.create!( nome: 'Roberto Conceição Gonzaga', email: 'roberto@totalrv.com.br', empresa_id: 355)
Contato.create!( nome: 'Milton Cesar Bueno Portes', email: 'milton.portes@tropiconet.com', empresa_id: 356)
Contato.create!( nome: 'Leandro Lima', email: 'leandro@tubaron.com.br', empresa_id: 357)
Contato.create!( nome: 'Cristiano Louchard Farias Sales', email: 'cristiano_louchard@hotmail.com', empresa_id: 358)
Contato.create!( nome: 'Daison Silveira Fonseca', email: 'daisonvclub@gmail.com', empresa_id: 359)
Contato.create!( nome: 'Marcos Antonio Americo de Oliveira', email: 'marcos.turbonett@hotmail.com', empresa_id: 360)
Contato.create!( nome: 'Humberto Barradas', email: 'hbarradas@redetv.com.br', empresa_id: 361)
Contato.create!( nome: 'Gerência GTIT', email: 'gtit@pucrs.rs.br', empresa_id: 362)
Contato.create!( nome: 'Paulo Roberto Pereira dos Santos', email: 'Paulo Roberto Pereira dos Santos', empresa_id: 363)
Contato.create!( nome: 'Vilmar Aguiar de Paula Segundo', email: 'vilmar@directbandalarga.com.br', empresa_id: 364)
Contato.create!( nome: 'Valdemar Melo', email: 'suporte@conecteinstale.com.br', empresa_id: 365)
Contato.create!( nome: 'Valdemar Melo', email: 'juridico@conectvca.com.br', empresa_id: 365)
Contato.create!( nome: 'Otacílio Lopes de Souza', email: 'otacilio@vante.com.br', empresa_id: 366)
Contato.create!( nome: 'Andréia Cristina', email: 'financeiro@vegastelecom.com', empresa_id: 367)
Contato.create!( nome: 'MAURO MEIRELLES', email: 'mauro@corp.vetorial.net', empresa_id: 368)
Contato.create!( nome: 'Alexandre Julião Evangelista', email: 'alexandre@viasultelecom.com.br', empresa_id: 369)
Contato.create!( nome: 'Mauricio Machado de Oliveira', email: 'mauricio@lig16.com', empresa_id: 370)
Contato.create!( nome: 'William', email: 'atendimento@viasul.net.br', empresa_id: 371)
Contato.create!( nome: 'Luiz Gustavo Ribeiro', email: 'gustavo@virtualcity.com.br', empresa_id: 372)
Contato.create!( nome: 'Neuri Antonio Almeida Ben ', email: 'neuriben@gmail.com', empresa_id: 373)
Contato.create!( nome: 'Edivaldo Pereira dos Santos', email: 'vision.19@hotmail.com', empresa_id: 374)
Contato.create!( nome: 'Edivaldo Pereira dos Santos', email: 'gerencia@rondonet-telecom.com.br', empresa_id: 374)
Contato.create!( nome: 'Ana Paula de Oliveira Lima Menezes', email: 'contato@vitorinonet.com.br', empresa_id: 375)
Contato.create!( nome: 'Ana Paula de Oliveira Lima Menezes', email: 'guilherme_menezes3@hotmail.com', empresa_id: 375)
Contato.create!( nome: 'Roque Alves de Siqueira', email: 'viva@vivanet-ltda.com.br', empresa_id: 376)
Contato.create!( nome: 'Carlos Alberto Delfino Correa', email: 'Carlos.ACorrea@telefonica.com', empresa_id: 377)
Contato.create!( nome: 'Alaelson Tatsch', email: 'alaelson@ntc.net.br', empresa_id: 378)
Contato.create!( nome: 'Marcos Marques', email: 'marcos.marques@wavetelecom.com.br', empresa_id: 379)
Contato.create!( nome: 'Edwilton de Batista- Eugenio', email: 'edwilton.batista@wdstelecom.com.br', empresa_id: 380)
Contato.create!( nome: 'José Leonardo Pedrozo', email: 'diretoria@wbmx.com.br', empresa_id: 381)
Contato.create!( nome: 'Wedenardo Pedro da Costa', email: 'wedenardo@gmail.com', empresa_id: 382)
Contato.create!( nome: 'Lucio Roberto Moura', email: 'moura.lucio@uol.com.br', empresa_id: 383)
Contato.create!( nome: 'Alexsander de Castro Reis', email: 'magela@flexanet.com.br', empresa_id: 384)
Contato.create!( nome: 'Gilmar Soares', email: 'gilmar@windtel.com.br', empresa_id: 385)
Contato.create!( nome: 'Pedro Neto de Oliveira Aguiar', email: 'pedro@wlansistemas.com.br', empresa_id: 386)
Contato.create!( nome: 'Jeferson Pinow Zaminhan', email: 'jeferson@redewsp.com.br', empresa_id: 387)
Contato.create!( nome: 'Milton Candaten', email: 'svp.milton@gmail.com', empresa_id: 388)
Contato.create!( nome: 'Luiz Carlos Zancanella', email: 'luizcarlos@safeweb.com.br', empresa_id: 389)
Contato.create!( nome: 'Yzabella Kristina', email: 'ysabella@linkfire.com.br', empresa_id: 390)
Contato.create!( nome: 'Aureliano Gustavo de Queiroz Arantes', email: 'aurelianoarantes@zaptelecom.com.br', empresa_id: 391)
Contato.create!( nome: 'Pedro Brom Azeredo Neto', email: 'pedrobrom@jatainet.com.br', empresa_id: 392)
Contato.create!( nome: 'Eduardo Veloso', email: 'eduardovelozo@gmail.com', empresa_id: 392)
Contato.create!( nome: 'Luiz Felipe Zilio', email: 'zilio@redesulnet.com.br', empresa_id: 393)
Contato.create!( nome: 'Mauro Meirelles', email: 'mauro@corp.vetorial.net', empresa_id: 394)
Contato.create!( nome: 'Cristiano Marques Zottis', email: 'cristiano@telnetprovedor.com.br', empresa_id: 395)
Contato.create!( nome: 'Carlo Zanette', email: 'carlo@zcafe.com.br', empresa_id: 396)

