Empresa.create!(razao: '25ª CIRCUNSCRIÇÃO DE SERVIÇO MILITAR',nome_fantasia: '25ª CIRCUNSCRIÇÃO DE SERVIÇO MILITAR',cnpj: '09644710000129',regional: 'Governo',sap: '')
Empresa.create!(razao: 'A. C. VERA FILHO TELECOMUNICAÇÕES E INFORMATICA - ME',nome_fantasia: 'VELOSTER INTERNET E TELECOMUNICAÇÕES',cnpj: '10275431000114',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'ABC WIFI TELECOM LTDA - ME',nome_fantasia: 'ABC WIFI',cnpj: '04913154000125',regional: 'Belém',sap: '')
Empresa.create!(razao: 'ABENET PROVEDORA DE ACESSO A INTERNET ME',nome_fantasia: 'ABENET',cnpj: '03576095000184',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'ADP3 TELECOMUNICACOES LTDA',nome_fantasia: 'ADP3 TELECOM',cnpj: '13954560000127',regional: 'São Paulo',sap: '')
Empresa.create!(razao: 'AGENCIA BRASILEIRA DE INTELIGENCIA-ABIN-GSI-PR',nome_fantasia: 'AGENCIA BRASILEIRA DE INTELIGENCIA-ABIN',cnpj: '01175497000141',regional: 'Governo',sap: '')
Empresa.create!(razao: 'AGÊNCIA NACIONAL DE ÁGUAS',nome_fantasia: 'ANA',cnpj: '04204444000108',regional: 'Governo',sap: '')
Empresa.create!(razao: 'AGÊNCIA NACIONAL DE TELECOMUNICAÇÕES',nome_fantasia: 'ANATEL',cnpj: '02030715000112',regional: 'Governo',sap: '')
Empresa.create!(razao: 'AGÊNCIA NACIONAL DE TRANSPORTES TERRESTRES',nome_fantasia: 'ANTT',cnpj: '04898488000177',regional: 'Governo',sap: '')
Empresa.create!(razao: 'AGENCIA NACIONAL DO CINEMA',nome_fantasia: 'ANCINE',cnpj: '04884574000120',regional: 'Rio de Janeiro',sap: '')
Empresa.create!(razao: 'AGÊNCIA NACIONAL DO PETRÓLEO -  GÁS NATURAL E BIOCOMBUSTÍVEIS',nome_fantasia: 'ANP',cnpj: '02313673000208',regional: 'Governo',sap: '')
Empresa.create!(razao: 'AGO BRASIL INTERNET LTDA - ME',nome_fantasia: 'IWP INTERNET',cnpj: '09410651000124',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'AKTO TECNOLOGIA EIRELI - EPP',nome_fantasia: 'AKTO TECNOLOGIA',cnpj: '07760064000130',regional: 'Belém',sap: '')
Empresa.create!(razao: 'ALESSIO & LONGHI LTDA',nome_fantasia: 'SGNET-RS',cnpj: '04022409000160',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'ALFA TELECOMUNICAÇOES LTDA - ME',nome_fantasia: 'WOMP',cnpj: '05492370000107',regional: 'Belém',sap: '')
Empresa.create!(razao: 'ALIANCA TELECOM INTERNET E INFORMATICA LTDA - ME',nome_fantasia: 'ON LINE VALE',cnpj: '13126124000160',regional: 'São Paulo',sap: '')
Empresa.create!(razao: 'ALMEIDA E GOMES LTDA - ME',nome_fantasia: 'VIRTUAL STAR',cnpj: '08407644000100',regional: 'Belém',sap: '')
Empresa.create!(razao: 'ALPINET INFORMÁTICA LTDA - ME',nome_fantasia: 'ALPINET',cnpj: '04113958000140',regional: 'Rio de Janeiro',sap: '')
Empresa.create!(razao: 'ANDRES REFATTE CHEGUHEN EIRELI - ME',nome_fantasia: 'TCHÊNET',cnpj: '18279167000107',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'APANET COMÉRCIO E SERVIÇO DE INTERNET  LTDA',nome_fantasia: 'Apanet',cnpj: '05830937000108',regional: 'Belém',sap: '')
Empresa.create!(razao: 'ARANET COMUNICAÇÃO LTDA - EPP',nome_fantasia: 'ARANET SOLUÇÕES EM INTERNET',cnpj: '09503823000104',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'ARION SERVIÇOS DE TELECOMUNICAÇÕES LTDA.',nome_fantasia: 'Arion Services',cnpj: '20059578000120',regional: 'São Paulo',sap: '')
Empresa.create!(razao: 'ARRAIS FALCÃO E SARAIVA CONSULTORIA E PRESTAÇÃO DE SERVIÇOS EM INTERNET LTDA - ME',nome_fantasia: 'MAIS NET TECNOLOGIA INTEGRADA',cnpj: '12033087000182',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'ARSENAL DE GUERRA DO RIO - AGR',nome_fantasia: 'AGR',cnpj: '09944413000107',regional: 'Rio de Janeiro',sap: '')
Empresa.create!(razao: 'ASSOCIAÇÃO INSTITUTO DE TECNOLOGIA DE PERNAMBUCO',nome_fantasia: 'ITEP-OS',cnpj: '05774391000115',regional: 'Governo',sap: '')
Empresa.create!(razao: 'AVANÇAR ENGENHARIA DE COMPUTAÇÃO EIRELI EPP',nome_fantasia: 'AVANÇAR',cnpj: '09418723000180',regional: 'Rio de Janeiro',sap: '')
Empresa.create!(razao: 'AVNET COMUNICAÇÃO SEM FRONTEIRAS LTDA',nome_fantasia: 'INTERNETKA',cnpj: '10455378000133',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'AXTELECOM TELECOMUNICAÇÕES LTDA',nome_fantasia: 'Axtelecom',cnpj: '00538593000144',regional: 'Rio de Janeiro',sap: '')
Empresa.create!(razao: 'AXXESS TELECOMUNICAÇÕES LTDA - ME',nome_fantasia: 'AXXESS TELECOMUNICAÇÕES',cnpj: '09382790000191',regional: 'Belém',sap: '')
Empresa.create!(razao: 'BALBINO SERVIÇO DE COMUNICAÇÃO MULTIMIDIA LTDA - ME',nome_fantasia: 'C.B.S INFORMÁTICA',cnpj: '10561685000107',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'BALSAS NET LTDA - ME',nome_fantasia: 'BALSAS NET',cnpj: '12905686000149',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'BANCO CENTRAL DO BRASIL',nome_fantasia: 'Banco Central do Brasil',cnpj: '0038166000105',regional: 'Governo',sap: '')
Empresa.create!(razao: 'BELEZA NETWORK PROVEDOR DE INTERNET LTDA - ME',nome_fantasia: 'BLZ NET',cnpj: '08204233000118',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'BERTONE MARTINS ALCANFOR',nome_fantasia: 'INFORTEL',cnpj: '10779392000192',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'BOMFIM & SOUSA LTDA',nome_fantasia: 'BOMFIM & SOUSA',cnpj: '07000765000170',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'BORBA PROVEDOR LTDA',nome_fantasia: 'NET LINE',cnpj: '23428899000143',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'BOSSNET PROVEDOR DE INTERNET LTDA',nome_fantasia: 'BOSSNET',cnpj: '14702958000139',regional: 'Belém',sap: '')
Empresa.create!(razao: 'BRASIL DIGITAL SERVIÇOS DE INFORMÁTICA E COMÉRCIO LTDA - ME',nome_fantasia: 'BRASIL DIGITAL',cnpj: '14629705000187',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'BRASIL DIGITAL TELECOMUNICAÇÕES LTDA.',nome_fantasia: 'BRDIGITAL',cnpj: '11966640000177',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'BRASIL NORTE TELECOMUNICAÇÕES LTDA - EPP',nome_fantasia: 'G3 TELECOM',cnpj: '17955033000198',regional: 'Belém',sap: '')
Empresa.create!(razao: 'BRASILNET INTERNET BANDA LARGA LTDA - ME',nome_fantasia: 'BRASILNET INTERNET BANDA LARGA LTDA - ME',cnpj: '07246932000168',regional: 'Belém',sap: '')
Empresa.create!(razao: 'BRISANET PREST. SERV. DE INTERNET ',nome_fantasia: 'BRISANET',cnpj: '04601397000128',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'BRPHONIA PROVEDOR IP LTDA',nome_fantasia: 'BRPHONIA PROVEDOR',cnpj: '10431131000187',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'BRSULNET TELECOM LTDA - EPP',nome_fantasia: 'BRSULNET',cnpj: '13338689000100',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'BRT COMÉRCIO DE PRODUTOS DE INFORMÁTICA LTDA - ME',nome_fantasia: 'BRT NETWORK',cnpj: '06203355000164',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'BYAL TELECOM LTDA. - EPP',nome_fantasia: 'BYALNET',cnpj: '03264131000174',regional: 'Rio de Janeiro',sap: '')
Empresa.create!(razao: 'C M C NOGUEIRA INFORMATICA LTDA',nome_fantasia: 'WIRELLESSNET',cnpj: '09615199000137',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'C M S MARTINS - ME',nome_fantasia: 'HC COMERCIO E SERVICOS',cnpj: '12523304000112',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'C P SARMENTO - ME',nome_fantasia: 'SIVNET',cnpj: '05383078000156',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'C. S. TAVARES - ME',nome_fantasia: 'VIP ONLINE',cnpj: '03481331000189',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'C.M & TELECOMUNICACÕES PROVEDOR NET DO BRASIL LTDA - ME',nome_fantasia: 'LINK WAP TELECOMUNICAÇÕES',cnpj: '08646215000196',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'CAIXA ECONÔMICA FEDERAL',nome_fantasia: 'CEF',cnpj: '00360305000104',regional: 'Governo',sap: '')
Empresa.create!(razao: 'CAPIXABA TELECOMUNICAÇÃO',nome_fantasia: 'NET SUPER',cnpj: '12274997000157',regional: 'Rio de Janeiro',sap: '')
Empresa.create!(razao: 'CAROLINA ONLINE COMUNICAÇÕES MULTIMÍDIA ',nome_fantasia: 'Carolina Online',cnpj: '10735362000184',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'CCA - COMANDO DA AERONAUTICA',nome_fantasia: 'CENTRO DE COMPUTACAO DA AERONAUTICA DO RIO DE JANEIRO',cnpj: '00394429000372',regional: 'Rio de Janeiro',sap: '')
Empresa.create!(razao: 'CEMIG TELECOMUNICAÇÕES S.A.',nome_fantasia: 'Cemig Telecom',cnpj: '02983428000127',regional: 'Rio de Janeiro',sap: '')
Empresa.create!(razao: 'CENTRO GESTOR E OPERACIONAL DO SISTEMA DE PROTEÇÃO DA AMAZÔNIA',nome_fantasia: 'CENSIPAM',cnpj: '07129796000126',regional: 'Governo',sap: '')
Empresa.create!(razao: 'CENTRO OESTE TELECOM LTDA',nome_fantasia: 'Maxx Speed Internet',cnpj: '10955922000106',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'CERILUZ PROVEDORES DE INTERNET LTDA',nome_fantasia: 'CERILUZ',cnpj: '15420705000135',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'CIA DE PROCES. DE DADOS MUNICÍPIO DE PORTO ALEGRE',nome_fantasia: 'PROCEMPA',cnpj: '89398473000100',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'CILNET COMUNICAÇÃO E INFORMATICA LTDA',nome_fantasia: 'FASTERNET',cnpj: '04127856000183',regional: 'São Paulo',sap: '')
Empresa.create!(razao: 'CITEX - CENTRO INTEGRADO DE TELEMÁTICA DO EXÉRCITO',nome_fantasia: 'CITEX',cnpj: '07518297000120',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'CITYDATA TELECOMUNICAÇÕES LTDA - ME',nome_fantasia: 'CITYDATA TELECOMUNICAÇÕES LTDA - ME',cnpj: '09336143000143',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'CLICK NET BRASIL INFORMÁTICA E TELECOMUNICAÇÕES',nome_fantasia: 'CLICK NET',cnpj: '11325221000237',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'CLINIC INFORMÁTICA LTDA',nome_fantasia: 'Net Velox',cnpj: '07764696000171',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'COELHO TECNOLOGIA EIRELI - ME',nome_fantasia: 'COELHO TECNOLOGIA',cnpj: '08182940000150',regional: 'Belém',sap: '')
Empresa.create!(razao: 'COLINA SERVIÇOS DE TELECOMUNICAÇÕES',nome_fantasia: 'COLINA',cnpj: '00608711000143',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'COLOG - COMANDO LOGÍSTICO DO EXÉRCITO',nome_fantasia: 'COLOG',cnpj: '00394452025009',regional: 'Governo',sap: '')
Empresa.create!(razao: 'COMAER - COMANDO DA AERONAUTICA',nome_fantasia: 'COMAER',cnpj: '00394429013350',regional: 'Governo',sap: '')
Empresa.create!(razao: 'COMANDO DA 8ª REGIAO MILITAR E 8ª DIVISAO DO EXERCITO',nome_fantasia: 'COMANDO DA 8ª REGIAO MILITAR E 8ª DIVISA',cnpj: '09635270000143',regional: 'Governo',sap: '')
Empresa.create!(razao: 'COMANDO DO COMANDO MILITAR DA AMAZÔNIA',nome_fantasia: 'COMANDO DO COMANDO MILITAR DA AMAZÔNIA',cnpj: '10207029000100',regional: 'Governo',sap: '')
Empresa.create!(razao: 'COMANDO DO EXERCITO',nome_fantasia: 'CENTRO DE DEFESA CIBERNÉTICA - CDCIBER',cnpj: '00394452053487',regional: 'Governo',sap: '')
Empresa.create!(razao: 'COMANDO DO EXERCITO (2)',nome_fantasia: 'CENTRO DE INTELIGENCIA DO EXERCITO',cnpj: '00394452055188',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'COMANDO MILITAR SUL',nome_fantasia: 'COMANDO MILITAR SUL',cnpj: '96068200001004',regional: 'Governo',sap: '')
Empresa.create!(razao: 'COMARCA PIUMHI LTDA',nome_fantasia: 'VITAL NET',cnpj: '41814930000166',regional: 'Rio de Janeiro',sap: '')
Empresa.create!(razao: 'COMPANHIA DE PESQUISA DE RECURSOS MINERAIS',nome_fantasia: 'CPRM',cnpj: '00091652001401',regional: 'Governo',sap: '')
Empresa.create!(razao: 'COMPUSERVICE EMPREENDIMENTOS LTDA',nome_fantasia: 'COMPUSERVICE',cnpj: '02985578000170',regional: 'Belém',sap: '')
Empresa.create!(razao: 'CONDOMINIO BELVEDERE',nome_fantasia: 'CONDOMINIO BELVEDERE',cnpj: '09310842000114',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'CONECTMAIS COMUNICAÇÕES LTDA. ME',nome_fantasia: 'CONECTMAIS TELECOM',cnpj: '10723327000145',regional: 'Rio de Janeiro',sap: '')
Empresa.create!(razao: 'CONNECTION MULTIMÍDIA TELECOMUNICAÇÕES  LTDA',nome_fantasia: 'SADNET',cnpj: '09604757000169',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'CONSELHO DE ARQUITETURA E URBANISMO DO BRASIL',nome_fantasia: 'CAU',cnpj: '14702767000177',regional: 'Governo',sap: '')
Empresa.create!(razao: 'CONSELHO REGIONAL DE ENFERMAGEM DE MINAS GERAIS',nome_fantasia: 'COREN-MG',cnpj: '21699889000117',regional: 'Rio de Janeiro',sap: '')
Empresa.create!(razao: 'COONEXÃO TELECOM E INFORMÁTICA EIRELI',nome_fantasia: 'COONEXÃO INFORMATICA',cnpj: '12848641000180',regional: 'Belém',sap: '')
Empresa.create!(razao: 'COPEL TELECOMUNICAÇÕES S-A',nome_fantasia: 'COPEL',cnpj: '04368865000166',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'COPREL TELECOM LTDA',nome_fantasia: 'COPREL',cnpj: '09238990000175',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'CRISTIANO NUNES DA SILVA - ME',nome_fantasia: 'TURBONET',cnpj: '14506948000128',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'CST SERVIÇOS DE INTERNET LTDA-ME',nome_fantasia: 'CONECTLAN SERVIÇOS  DE INTERNET',cnpj: '09473770000126',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'CTBC MULTIMÍDIA DATA NET S-A',nome_fantasia: 'ALGAR TELECOM',cnpj: '04622116000113',regional: 'Rio de Janeiro',sap: '')
Empresa.create!(razao: 'D & D INFORMATICA LTDA - ME',nome_fantasia: 'LIDER INFORMATICA',cnpj: '03897438000102',regional: 'Belém',sap: '')
Empresa.create!(razao: 'DB3 SERVIÇOS DE TELECOMUNICAÇÕES',nome_fantasia: 'DB3 TELECOM',cnpj: '41644220000135',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'DBSERVER ASSESSORIA E SISTEMA DE INFORMAÇÃO',nome_fantasia: 'DBSERVER',cnpj: '68729649000181',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'DE ALMEIDA E MENSCH - PROVEDOR DE INTERNET LTDA',nome_fantasia: 'VIRTUAL INFORMÁTICA PROVEDOR DE INTERNET',cnpj: '10415167000177',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'DELTA BROADBAND TELECOM PROVEDORES INTERNET',nome_fantasia: 'DBT',cnpj: '16550861000183',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'DEPARTAMENTO DE POLÍCIA RODOVIÁRIA FEDERAL',nome_fantasia: 'DPRF',cnpj: '00394494010441',regional: 'Governo',sap: '')
Empresa.create!(razao: 'DEPARTAMENTO GERAL DO PESSOAL - COMANDO DO EXÉRCITO',nome_fantasia: 'DEPARTAMENTO GERAL DO PESSOAL (DGP)',cnpj: '00394452027133',regional: 'Governo',sap: '')
Empresa.create!(razao: 'DIEGO HINZ SOARES - ME',nome_fantasia: 'WILLYNET',cnpj: '09720168000146',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'DJEAN OLIVEIRA BEZERRA - ME',nome_fantasia: 'SEM FRONTEIRAS - INTERNET BANDA LARGA',cnpj: '11972556000166',regional: 'Belém',sap: '')
Empresa.create!(razao: 'DL SOUZA E CIA LTDA',nome_fantasia: 'SPEED NET',cnpj: '12450258000179',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'DYNATEC INFORMATICA LTDA - ME',nome_fantasia: 'DYNATEC INFORMÁTICA',cnpj: '08636618000154',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'E. MARCIANO DA SILVA E CIA LTDA',nome_fantasia: 'GARRA TELECOM',cnpj: '12523391000108',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'EBER DEJANI PEREIRA DE ALBERNAZ E CIA LTDA - ME',nome_fantasia: 'PROVEDOR UNIVERSAL',cnpj: '10940364000105',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'ELETRONORTE - CENTRAIS ELÉTRICAS DO NORTE DO BRASIL S.A.',nome_fantasia: 'ELETRONORTE',cnpj: '00357038000116',regional: 'Governo',sap: '')
Empresa.create!(razao: 'ELETROSUL CENTRAIS ELÉTRICAS S.A.',nome_fantasia: 'ELETROSUL',cnpj: '00073957000168',regional: 'Governo',sap: '')
Empresa.create!(razao: 'EMPRESA BRASIL DE COMUNICACAO S.A. - EBC',nome_fantasia: 'EBC TV BRASIL',cnpj: '09168704000142',regional: 'Governo',sap: '')
Empresa.create!(razao: 'EMPRESA BRASILEIRA DE CORREIOS E TELÉGRAFOS',nome_fantasia: 'CORREIOS',cnpj: '34028316000103',regional: 'Governo',sap: '')
Empresa.create!(razao: 'EMPRESA BRASILEIRA DE HEMODERIVADOS E BIOTECNOLOGIA - HEMOBRAS',nome_fantasia: 'HEMOBRAS',cnpj: '07607851000146',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'EMPRESA CATARINENSE DE TECNOLOGIA EM TELECOMUNICAÇÕES LTDA',nome_fantasia: 'OLÉ TELECOM',cnpj: '08519692000190',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'EMPRESA DE PROCESSAMENTO DE DADOS DO ESTADO DO PARA',nome_fantasia: 'PRODEPA',cnpj: '05059613000118',regional: 'Governo',sap: '')
Empresa.create!(razao: 'EMPRESA DE TECNOLOGIA E INFORMACOES DA PREVIDENCIA - DATAPREV',nome_fantasia: 'DATAPREV',cnpj: '42422253001418',regional: 'Governo',sap: '')
Empresa.create!(razao: 'ENGEPLUS TELECOM LTDA - EPP',nome_fantasia: 'ENGEPLUS TELECOM',cnpj: '80995822000199',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'ENGETEC TECNOLOGIA S.A.',nome_fantasia: 'ENGETEC',cnpj: '10780881000164',regional: 'Rio de Janeiro',sap: '')
Empresa.create!(razao: 'ESTREITONET LTDA',nome_fantasia: 'ESTREITONET',cnpj: '08417524000194',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'EXÉRCITO BRASILEIRO - GABINETE DO COMANDANTE',nome_fantasia: 'CIE - Centro de Inteligência do Exército',cnpj: '00394452000103',regional: 'Governo',sap: '')
Empresa.create!(razao: 'EXÉRCITO BRASILEIRO ? 7º CENTRO DE COMUNICAÇÕES E  TELEMÁTICA DE ÁREA',nome_fantasia: 'EXÉRCITO BRASILEIRO',cnpj: '07518297000120',regional: 'Governo',sap: '')
Empresa.create!(razao: 'EYES NWHERE SIST. INTELIG. DE IMAGEM',nome_fantasia: 'EYES NWHERE',cnpj: '07244008000223',regional: 'Belém',sap: '')
Empresa.create!(razao: 'F J R W ASSOCIADOS LTDA - ME',nome_fantasia: 'ULTRANET',cnpj: '20379501000138',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'FAVIERO DUARTE & CIA LTDA',nome_fantasia: 'BNET',cnpj: '01387236000195',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'FAZENDO MAIS TECNOLOGIA AVANÇADA PARA ENVENTOS LTDA',nome_fantasia: 'FAZENDO MAIS',cnpj: '12487878000182',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'FERNANDO NET & TELECOM',nome_fantasia: 'FERNANDO NET',cnpj: '10217540000185',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'FIGUEIREDO & SILVA LTDA',nome_fantasia: 'ARJNET',cnpj: '20900302000123',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'FIUZA INFORMÁTICA & TELECOMUNICAÇÃO LTDA - ME',nome_fantasia: 'VENON CONNECT',cnpj: '20212207000137',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'FLÁVIO GARCIA FERREIRA - ME',nome_fantasia: 'CAIAPONIANET',cnpj: '11840992000181',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'FLAVIO JOSE PENSO JUNIOR - ME',nome_fantasia: 'INEXA TECNOLOGIA',cnpj: '01836999000176',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'FONTE NOVA NEGÓCIOS E PARTICIPAÇÕES S.A.',nome_fantasia: 'FNP',cnpj: '08906994000111',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'FRANCISCA EDILEUZA MELO Â',nome_fantasia: 'EDI MELO -  INFORMÁTICA -  SERVIÇOS E TELEC',cnpj: '00795293000140',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'FULL 3 TELECOM LTDA - ME',nome_fantasia: 'FULL 3 TELECOM',cnpj: '20460413000166',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'FUNDAÇÃO  VILA OLÍMPICA - FVO',nome_fantasia: 'FVO',cnpj: '34585380000195',regional: 'Governo',sap: '')
Empresa.create!(razao: 'FUNDAÇÃO ALEXANDRE DE GUSMÃO - FUNAG',nome_fantasia: 'FUNAG',cnpj: '00662197000124',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'FUNDAÇÃO OSWALDO CRUZ',nome_fantasia: 'FIOCRUZ CEARA',cnpj: '33781055006761',regional: 'Governo',sap: '')
Empresa.create!(razao: 'FURNAS CENTRAIS ELÉTRICA S.A.',nome_fantasia: 'FURNAS',cnpj: '23274194000119',regional: 'Governo',sap: '')
Empresa.create!(razao: 'FURTADO & FURTADO PROVEDORES LTDA - ME',nome_fantasia: 'INTERLINE',cnpj: '18174153000110',regional: 'Belém',sap: '')
Empresa.create!(razao: 'G8 NETWORKS LTDA',nome_fantasia: 'G8 Networks',cnpj: '02926037000170',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'GENESIS COMÉRCIO DE COMPUTADORES LTDA - ME',nome_fantasia: 'GENESIS INFORMÁTICA',cnpj: '06129343000137',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'GIGABYTE NETWORK COMÉRCIO E SERVIÇOS EIRELI - EPP',nome_fantasia: 'GIGABYTE NETWORK',cnpj: '18671267000176',regional: 'Belém',sap: '')
Empresa.create!(razao: 'GINONET.COM.BR PROVEDORES DE ACESSO A RE',nome_fantasia: 'GO NETWORKS',cnpj: '09032588000130',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'GLOBAL VILLAGE TELECOM LTDA',nome_fantasia: 'GVT',cnpj: '03420926000124',regional: 'São Paulo',sap: '')
Empresa.create!(razao: 'GM INFORMÁTICA',nome_fantasia: 'MICROLINK INFORMATICA',cnpj: '02705128000186',regional: 'Rio de Janeiro',sap: '')
Empresa.create!(razao: 'GNET COMUNICAÇÕES E INFORM LTDA',nome_fantasia: 'GNET COMUNICAÇÕES',cnpj: '11739842000186',regional: 'Belém',sap: '')
Empresa.create!(razao: 'GNEX LTDA - ME',nome_fantasia: 'GNEX TELECOM',cnpj: '09011207000136',regional: 'Belém',sap: '')
Empresa.create!(razao: 'GOLD TELECOMUNICACOES LTDA - ME',nome_fantasia: 'GOLD LINK',cnpj: '20193955000110',regional: 'São Paulo',sap: '')
Empresa.create!(razao: 'GOVERNO DO ESTADO DE RONDÔNIA',nome_fantasia: 'GOVERNO DE RONDONIA',cnpj: '03693136000112',regional: 'Governo',sap: '')
Empresa.create!(razao: 'GRUPAMENTO DE APOIO LOGÍSTICO (GAL)',nome_fantasia: 'GRUPAMENTO DE APOIO LOGÍSTICO (GAL)',cnpj: '00394429017429',regional: 'Governo',sap: '')
Empresa.create!(razao: 'GRUPO CONECTA TELECOM SERVIÇOS DE TELECOMUNICAÇÕES LTDA.',nome_fantasia: 'GRUPO CONECTA',cnpj: '14959659000184',regional: 'Belém',sap: '')
Empresa.create!(razao: 'GTNET PROVEDOR DE ACESSO A INTERNET LTDA - ME',nome_fantasia: 'GTNET',cnpj: '08617194000180',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'GURISAT GURINET LTDA',nome_fantasia: 'GURISAT GURINET',cnpj: '02687221000105',regional: 'Rio de Janeiro',sap: '')
Empresa.create!(razao: 'GUSA NORDESTE S.A.',nome_fantasia: 'AVB - ACO VERDE DO BRASIL',cnpj: '07636657000270',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'H.R.B. LACERDA COMERCIO E SERVIÇOS - ME',nome_fantasia: 'PROVEDOR DE INTERNET CONEXAO NET',cnpj: '14809276000120',regional: 'Belém',sap: '')
Empresa.create!(razao: 'HALLEY TELECOM COMERCIO & SERVICOS LTDA - ME',nome_fantasia: 'RÁPIDO INTERNET BANDA LARGA',cnpj: '01003578000164',regional: 'Belém',sap: '')
Empresa.create!(razao: 'HENRIQUE HONÓRIO PEREIRA CABRAL',nome_fantasia: 'SHOPNET INFORMÁTICA',cnpj: '04011732000138',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'HONOS DATA EXCHANGE INFORMATICA LTDA - EPP',nome_fantasia: 'HONOS DATA EXCHANGE',cnpj: '07821488000167',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'I CESAR PEREIRA BARROS',nome_fantasia: 'NET TELECOM',cnpj: '22240475000198',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'I R TECNOLOGIA LTDA',nome_fantasia: 'FIBRALINK',cnpj: '09634107000166',regional: 'Belém',sap: '')
Empresa.create!(razao: 'I2 TELECOM TEC. DA INFORMAÇÃO  LTDA ME',nome_fantasia: 'I2 Telecom',cnpj: '12128581000120',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'I9 BRASÍLIA',nome_fantasia: 'I9 Brasília',cnpj: '06142903000193',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'IBL BANDA LARGA INTERNET INFORMÁTICA LTDA - ME',nome_fantasia: 'IBL',cnpj: '08854699000169',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'IMA TELECOM LTDA - ME',nome_fantasia: 'IMA TELECOM',cnpj: '10934273000167',regional: 'Rio de Janeiro',sap: '')
Empresa.create!(razao: 'IMPRENSA NACIONAL',nome_fantasia: 'IMPRENSA NACIONAL',cnpj: '04196645000100',regional: 'Governo',sap: '')
Empresa.create!(razao: 'INDNET TELECOMUNICAÇÕES LTDA -ME',nome_fantasia: 'INDNET',cnpj: '10356804000181',regional: 'Rio de Janeiro',sap: '')
Empresa.create!(razao: 'INFOBARRA SOLUÇÕES DE INFORMÁTICA LTDA - EPP',nome_fantasia: 'INFOBARRA',cnpj: '10388952000188',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'INFORMÁTICA DE MUNICÍPIOS ASSOCIADOS',nome_fantasia: 'IMA',cnpj: '48197859000169',regional: 'Governo',sap: '')
Empresa.create!(razao: 'INFOSYSTEM TELECOMUNICAÇÕES E INFORMÁTICA LTDA',nome_fantasia: 'INFOSYSTEM',cnpj: '13203392000138',regional: 'Rio de Janeiro',sap: '')
Empresa.create!(razao: 'INFRAERO - EMPRESA BRASILEIRA DE INFRAESTRUTURA AEROPORTUÁRIA',nome_fantasia: 'INFRAERO',cnpj: '00352294000110',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'INFRAMERICA CONCESSIONARIA DO AEROPORTO DE BRASILIA',nome_fantasia: 'INFRAMERICA',cnpj: '15559082000186',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'INSTITUTO BRASILEIRO DE GEOGRAFIA E ESTATÍSTICA',nome_fantasia: 'IBGE',cnpj: '33787094000140',regional: 'Governo',sap: '')
Empresa.create!(razao: 'INSTITUTO BRASILEIRO DE TURISMO',nome_fantasia: 'EMBRATUR',cnpj: '33741794000101',regional: 'Governo',sap: '')
Empresa.create!(razao: 'INSTITUTO BRASILEIRO DO MEIO AMBIENTE E DOS RECURSOS NATURAIS RENOVAVEIS',nome_fantasia: 'GERENCIA EXECUTIVA DO IBAMA NO DISTRITO FEDERAL',cnpj: '03659166000706',regional: 'Governo',sap: '')
Empresa.create!(razao: 'INSTITUTO CAMPUS PARTY',nome_fantasia: 'CAMPUS PARTY',cnpj: '10912323000105',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'INSTITUTO CHICO MENDES DE CONSERVACAO DA BIODIVERSIDADE',nome_fantasia: 'ICMBIO',cnpj: '08829974000275',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'INSTITUTO DE PESQUISA ECONOMICA APLICADA',nome_fantasia: 'IPEA',cnpj: '33892175000100',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'INSTITUTO FEDERAL DE EDUCAÇÃO - CIÊNCIAS E TECNOLOGIA DO CEARA',nome_fantasia: 'IFCE',cnpj: '10744098000900',regional: 'Governo',sap: '')
Empresa.create!(razao: 'INTELIG TELECOMUNICAÇÕES LTDA',nome_fantasia: 'INTELIG',cnpj: '02421421000111',regional: 'Rio de Janeiro',sap: '')
Empresa.create!(razao: 'INTERFIBRAS TELECOMUNICAÇÕES LTDA - EPP',nome_fantasia: 'INTERFIBRAS',cnpj: '20005969000162',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'INTERNEXA BRASIL OPERADORA DE TELECOMUNICAÇÕES S.A.',nome_fantasia: 'INTERNEXA BRASIL',cnpj: '11620561000100',regional: 'São Paulo',sap: '')
Empresa.create!(razao: 'INTERVALE TELECOM LTDA ME',nome_fantasia: 'INTERVALE',cnpj: '12244449000184',regional: 'São Paulo',sap: '')
Empresa.create!(razao: 'IP CARRIER TELECOM DO BRASIL EIRELI',nome_fantasia: 'IP CARRIER',cnpj: '10628267000181',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'IP2TEL SERVICOS DE COMUNICACAO MULTIMIDIA LTDA - ME',nome_fantasia: 'YES COMMUNICATIONS',cnpj: '17493657000130',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'IPINFO TELECOM E INFORMÁTICA ME',nome_fantasia: 'IPINFO',cnpj: '03455506000183',regional: 'Rio de Janeiro',sap: '')
Empresa.create!(razao: 'ISOTELCO LTDA - EPP',nome_fantasia: 'ISOTELCO',cnpj: '83343558000105',regional: 'Belém',sap: '')
Empresa.create!(razao: 'ITNET LTDA - ME',nome_fantasia: 'ITNET',cnpj: '04690098000107',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'J DA L MORAES TELECOMUNICAÇÕES - ME',nome_fantasia: 'MEGASOFT',cnpj: '07677911000105',regional: 'Belém',sap: '')
Empresa.create!(razao: 'J. & R. NETWORK PROVEDOR DE INTERNET LTDA. - ME',nome_fantasia: 'MEGA NET',cnpj: '19604109000166',regional: 'São Paulo',sap: '')
Empresa.create!(razao: 'JC TELECOM SERVIÇOS DE TELECOMUNICAÇÕES LTDA - EPP - FILIAL',nome_fantasia: 'JC TELECOM',cnpj: '04955538000453',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'JC TELECOM SERVIÇOS DE TELECOMUNICAÇÕES LTDA - EPP - MATRIZ',nome_fantasia: 'JC  INFORMATICA',cnpj: '04955538000100',regional: 'Belém',sap: '')
Empresa.create!(razao: 'JOAO JOSE ALVES BATISTA - ME',nome_fantasia: 'IDEAL TECNOLOGIA',cnpj: '33668484000109',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'JOSÉ EDUARDO MACHADO DA VEIGA E CIA LTDA',nome_fantasia: 'OPEN TECNOLOGIA',cnpj: '00799810000150',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'JR NET INFORMÁTICA LTDA - ME',nome_fantasia: 'GOIASNET',cnpj: '11106227000132',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'JUÇARA MARIA SILVA CARVALHO - ME',nome_fantasia: 'ESPERANTINA NET',cnpj: '20049543000100',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'JULIO DE SOUZA FRANCO NETO EIRELI - EPP',nome_fantasia: 'INFORTREAD',cnpj: '11460137000145',regional: 'Belém',sap: '')
Empresa.create!(razao: 'JUNTO TELECOM SERVIÇOS DE TELECOMUNICAÇÕES LTDA.',nome_fantasia: 'JUNTO TELECOM SERVIÇOS DE TELECOMUNICAÇÕES LTDA.',cnpj: '17192192000935',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'JÚPITER TELECOMUNICAÇÕES E INFORMÁTICA  LTDA',nome_fantasia: 'JÚPITER INFORMÁTICA',cnpj: '01625636000191',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'K S FERREIRA - ME',nome_fantasia: 'LINKDATA INFORMÁTICA E TELECOMUNICACOES',cnpj: '13766044000179',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'KARINE NEVES COELHO',nome_fantasia: 'NIPPONTEC TELECOMUNICAÇÕES',cnpj: '05875227000102',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'L A P GAITKOSKI',nome_fantasia: 'CONEXOES.NET',cnpj: '19168390000131',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'L. BATISTA E SOUSA EIRELI - ME',nome_fantasia: 'REGIONALWEB TELECOMUNICAÇÕES',cnpj: '21864406000192',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'L.C. DE CARVALHO CARNEIRO',nome_fantasia: 'NETSYSTEM INFORMÁTICA',cnpj: '10669397000162',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'L.V. DOS SANTOS - INFORMATICA - ME',nome_fantasia: 'ANDRASTA TI',cnpj: '13568652000179',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'LAGOS NET INTERNET BANDA LARGA LTDA',nome_fantasia: 'LAGOS NET',cnpj: '08588656000189',regional: 'Rio de Janeiro',sap: '')
Empresa.create!(razao: 'LAN SOLUTIONS INFORMATICA LTDA-ME',nome_fantasia: 'INTERLANS TELECOM',cnpj: '06292238000114',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'LG CONSULTORIA EM ADMINISTRAÇÃO E TECNOLOGIA LTDA',nome_fantasia: 'GDC TECNOLOGIA',cnpj: '08862565000190',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'LG PROVEDOR E SOLUÇÕES EM INFORMATICA LTDA',nome_fantasia: 'PHNET Telecom',cnpj: '11897935000139',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'LIGO TELECOMUNICAÇÕES LTDA',nome_fantasia: 'LIGO TELECOM',cnpj: '09648857000197',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'LIMA & CARVALHO',nome_fantasia: 'TELECOM & WIFI',cnpj: '10436597000175',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'LINHA LIVRE INTERNET LTDA - EPP',nome_fantasia: 'FLIN TELECOM',cnpj: '04324565000185',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'LINHAS DO XINGU TRANSMISSORA DE ENERGIA',nome_fantasia: 'LINHAS DO XINGU',cnpj: '10240186000290',regional: 'Belém',sap: '')
Empresa.create!(razao: 'LOGTEL TELECOM E INFORMATICA LTDA',nome_fantasia: 'LOGTEL',cnpj: '08505502000186',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'LUCARONI TELECOM LTDA',nome_fantasia: 'NET MAIS TELECOM',cnpj: '17310450000183',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'LUZIANE DOS SANTOS SAGMEISTER',nome_fantasia: 'LUZIANE DOS SANTOS',cnpj: '22521436000169',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'M S DUARTE - ME',nome_fantasia: 'MSD INFORMÁTICA',cnpj: '06064368000108',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'MAIS INTERNET LTDA - ME',nome_fantasia: 'MAIS INTERNET',cnpj: '11832927000104',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'MAP PIUMHI LTDA - ME',nome_fantasia: 'MAP TELECOM',cnpj: '12997155000123',regional: 'Rio de Janeiro',sap: '')
Empresa.create!(razao: 'MARCIO MEIRELES DE SOUZA INFORMATICA - ME',nome_fantasia: 'MARTZ INFORMATICA',cnpj: '14086676000154',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'MASTER DATA TELECOMUNICACOES LTDA - ME',nome_fantasia: 'MASTER DATA NET',cnpj: '12405111000167',regional: 'Rio de Janeiro',sap: '')
Empresa.create!(razao: 'MASTER ONLINE PROVEDOR SCM LTDA - ME',nome_fantasia: 'MASTER ONLINE',cnpj: '12578562000104',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'MAX TELECOMUNICAÇÕES LTDA',nome_fantasia: 'MAXIMIDIA',cnpj: '07793212000112',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'MAXIMA SEGURANÇA E TELECOMUNICAÇÕES LTDA.',nome_fantasia: 'MAXIMA',cnpj: '22666171000197',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'MAXIS TELECOMUNICAÇÕES LTDA - ME',nome_fantasia: 'MAXIS TELECOM',cnpj: '19694566000199',regional: 'Rio de Janeiro',sap: '')
Empresa.create!(razao: 'MD CONNECT TELECOMUNICAÇÕES LTDA - ME',nome_fantasia: 'MD CONNECT TELECOM',cnpj: '08426804000169',regional: 'Rio de Janeiro',sap: '')
Empresa.create!(razao: 'MEGABYTE PROVEDOR INTERNET LTDA',nome_fantasia: 'MEGABYTE',cnpj: '09434753000180',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'METROREC - COMPANHIA BRASILEIRA DE TRENS URBANOS - CBTU',nome_fantasia: 'METROREC',cnpj: '42357483000630',regional: 'Governo',sap: '')
Empresa.create!(razao: 'MH INTEGRAÇÃO REPARAÇÃO E INSTALAÇÃO EM INFORMÁTICA LTDA - ME',nome_fantasia: 'ENGETRONICS FÁBRICA DE SOLUÇÕES',cnpj: '08145394000188',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'MINISTÉRIO DA CIÊNCIA -  TECNOLOGIA -  INOVAÇÃO E COMUNICAÇÕES -  MCTIC',nome_fantasia: 'MCTIC',cnpj: '03132745000100',regional: 'Governo',sap: '')
Empresa.create!(razao: 'MINISTERIO DA CULTURA',nome_fantasia: 'COORDENACAO GERAL DE RECURSOS HUMANOS SAG-MINC',cnpj: '01264142000714',regional: 'Governo',sap: '')
Empresa.create!(razao: 'MINISTÉRIO DA DEFESA',nome_fantasia: 'MINISTÉRIO DA DEFESA',cnpj: '03277610000125',regional: 'Governo',sap: '')
Empresa.create!(razao: 'MINISTERIO DA INDUSTRIA -  COMERCIO EXTERIOR E SERVICOS',nome_fantasia: 'COORDENACAO GERAL DE SERVICOS GERAIS - MDIC',cnpj: '00394478000224',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'MINISTÉRIO DA JUSTIÇA',nome_fantasia: 'MINISTÉRIO DA JUSTIÇA',cnpj: '00394494001370',regional: 'Governo',sap: '')
Empresa.create!(razao: 'MINISTÉRIO DA SAÚDE',nome_fantasia: 'MINISTÉRIO DA SAÚDE',cnpj: '00530493000171',regional: 'Governo',sap: '')
Empresa.create!(razao: 'MINISTÉRIO DAS CIDADES',nome_fantasia: 'COORDENACAO-GERAL DE RECURSOS LOGISTICOS',cnpj: '05465986000350',regional: 'Governo',sap: '')
Empresa.create!(razao: 'MINISTERIO DE MINAS E ENERGIA',nome_fantasia: 'GABINETE DO MINISTRO',cnpj: '37115383000153',regional: 'Governo',sap: '')
Empresa.create!(razao: 'MINISTERIO DO MEIO AMBIENTE',nome_fantasia: 'SERVIÇO FLORESTAL BRASILEIRO - SFB',cnpj: '37115375000883',regional: 'Governo',sap: '')
Empresa.create!(razao: 'MINISTÉRIO DO MEIO AMBIENTE - MMA',nome_fantasia: 'MINISTÉRIO DO MEIO AMBIENTE',cnpj: '37115375000298',regional: 'Governo',sap: '')
Empresa.create!(razao: 'MINISTERIO DO PLANEJAMENTO -  ORCAMENTO E GESTAO - MP',nome_fantasia: 'COORDENACAO GERAL DE SERVICOS GERAIS - CSG',cnpj: '00489828000317',regional: 'Governo',sap: '')
Empresa.create!(razao: 'MINISTERIO DO TRABALHO - MTB',nome_fantasia: 'COORDENACAO-GERAL DE REC. LOGISTICOS - CGRL-MTPS',cnpj: '23612685000637',regional: 'Governo',sap: '')
Empresa.create!(razao: 'MINISTERIO DO TRABALHO E EMPREGO - MTE',nome_fantasia: 'MTE',cnpj: '37115367003348',regional: 'Governo',sap: '')
Empresa.create!(razao: 'MINISTÉRIO DO TURISMO',nome_fantasia: 'MIN. TURISMO',cnpj: '05457283000208',regional: 'Governo',sap: '')
Empresa.create!(razao: 'MINISTÉRIO DOS ESPORTES',nome_fantasia: 'MINISTÉRIO DOS ESPORTES',cnpj: '02961362000174',regional: 'Governo',sap: '')
Empresa.create!(razao: 'MINISTÉRIO PÚBLICO DO TRABALHO',nome_fantasia: 'MPT',cnpj: '26989715005503',regional: 'Governo',sap: '')
Empresa.create!(razao: 'MMA ACESSORIOS E SERVICOS DE INFORMATICA LTDA - EPP',nome_fantasia: 'MMA INFORMATICA',cnpj: '00655339000126',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'MULTLINK INFORMÁTICA E TEL. LTDA',nome_fantasia: 'MULTLINK TELECOM',cnpj: '10697880000150',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'N C COMÉRCIO DE EQUIPAMENTOS DE COMUNICAÇÃO LTDA - ME',nome_fantasia: 'FIBER NETWORK',cnpj: '14784071000137',regional: 'Belém',sap: '')
Empresa.create!(razao: 'N V SOUSA - ME',nome_fantasia: 'CIDADE ONLINE',cnpj: '09665162000113',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'NAJA TELECOMUNICAÇÕES LTDA-ME',nome_fantasia: 'NAJA TELECOMUNICAÇÕES LTDA.',cnpj: '09425544000170',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'NEOLOG TECNOLOGIA LTDA.',nome_fantasia: 'NEOLOG TECNOLOGIA',cnpj: '15146573000103',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'NET BARRETOS TECNOLOGIA - ME',nome_fantasia: 'NET BARRETOS',cnpj: '10687950000190',regional: 'São Paulo',sap: '')
Empresa.create!(razao: 'NET BRASILIA COMUNICAÇÃO E MULTIMIDIA LT',nome_fantasia: 'Vs Link',cnpj: '26499392000179',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'NET STORE TECNOLOGIA',nome_fantasia: 'NET STORE TECNOLOGIA',cnpj: '10213248000194',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'NET SUL INFORMATICA E SERVICOS DE PROVEDOR LTDA - ME',nome_fantasia: 'NET SUL',cnpj: '08092905000140',regional: 'Belém',sap: '')
Empresa.create!(razao: 'NET-BLADE COMUNICAÇÕES LTDA - ME',nome_fantasia: 'IUB TELECON',cnpj: '07875744000107',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'NEUBER MODESTO FONTOURA',nome_fantasia: 'LINK INFORMÁTICA',cnpj: '06111200000106',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'NIPPY NET INFORMÁTICA LTDA',nome_fantasia: 'Nippy Net Informática Ltda',cnpj: '09131028000132',regional: 'Rio de Janeiro',sap: '')
Empresa.create!(razao: 'NIQTURBO PIMENTEL E MOREIRA LTDA - ME',nome_fantasia: 'NIQTURBO',cnpj: '07584868000125',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'NOROESTECOM TELECOMUNICAÇÕES LTDA',nome_fantasia: 'NOROESTECOM',cnpj: '14603266000133',regional: 'São Paulo',sap: '')
Empresa.create!(razao: 'NORTELPA ENGENHARIA S-A',nome_fantasia: 'JUNTO TELECOM',cnpj: '01003694000183',regional: 'Belém',sap: '')
Empresa.create!(razao: 'OLIVEIRA & DECORATO LTDA ME',nome_fantasia: 'VIA EXPRESSA',cnpj: '03411348000160',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'OMINI TELECOMUNICAÇÕES LTDA.',nome_fantasia: 'Omni Telecom',cnpj: '09238990000175',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'ONDA G NETWORK TELECOMUNICAÇÕES LTDA',nome_fantasia: 'ONDA G',cnpj: '10293838000174',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'OOPS TELECOM LTDA - ME',nome_fantasia: 'OOPS TELECOM LTDA',cnpj: '16992716000152',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'OSIRNET INFO TELECOM LTDA-ME',nome_fantasia: 'OSIRNET',cnpj: '10773501000164',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'P4 TELECOM LTDA - EPP',nome_fantasia: 'P4 NET TELECOM',cnpj: '10703677000140',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'PAIM & ASSOCIADOS COMUNICAÇÃO LTDA',nome_fantasia: 'PAIM COMUNICAÇÃO',cnpj: '94425154000179',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'PAIVA SANTANA TELECOM COMUNICACOES LTDA - ME',nome_fantasia: 'SERVNET - BA',cnpj: '11174258000120',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'PAULO DE TARSO DE CARVALHO BAYMA FILHO',nome_fantasia: 'BAYMATECH-WIKI',cnpj: '11509434000138',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'PC SILVA HOUSE NET',nome_fantasia: 'HOUSE NET',cnpj: '09203570000153',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'PETRÓLEO BRASILEIRO S.A.',nome_fantasia: 'PETROBRAS',cnpj: '33000167000101',regional: 'Rio de Janeiro',sap: '')
Empresa.create!(razao: 'PHASE - PROJETOS -  SERVIÇOS DE ENGENHARIA E TELECOMUNICAÇÕES LTDA',nome_fantasia: 'PHASE ENGENHARIA',cnpj: '63859086000122',regional: 'Belém',sap: '')
Empresa.create!(razao: 'PLENITUDE E SISTEMAS LTDA - EPP',nome_fantasia: 'PLENITUDE E SISTEMAS LTDA - EPP',cnpj: '12667706000190',regional: 'Belém',sap: '')
Empresa.create!(razao: 'POLICANAL SERVIÇOS DE TELECOMUNICAÇÕES L',nome_fantasia: 'POLY CANAL',cnpj: '00316308000140',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'PONTOINFOR COMUNICAÇÃO LTDA - ME',nome_fantasia: 'PONTOINFOR',cnpj: '10761712000187',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'PONTUAL - NET SERVIÇOS DE TELECOMUNICAÇÕES LTDA - ME',nome_fantasia: 'PONTUAL - NET',cnpj: '12082987000110',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'PORTO VELHO TELECOMUNICAÇÕES LTDA',nome_fantasia: 'PORTO VELHO TELECOM',cnpj: '13114336000127',regional: 'Belém',sap: '')
Empresa.create!(razao: 'PREFEITURA  BARRETOS',nome_fantasia: 'PREFEITURA  BARRETOS',cnpj: '44780609000104',regional: 'Governo',sap: '')
Empresa.create!(razao: 'PREFEITURA  MUNICIPAL DE CIDADE  OCIDENTAL',nome_fantasia: 'PREF. MUN. CIDADE  OCIDENTAL',cnpj: '36862621000121',regional: 'Governo',sap: '')
Empresa.create!(razao: 'PREFEITURA  MUNICIPAL DE COLINAS DO TOCANTINS',nome_fantasia: 'PREFEITURA DE COLINAS',cnpj: '01795483000120',regional: 'Governo',sap: '')
Empresa.create!(razao: 'PREFEITURA DA CIDADE DO RIO DE JANEIRO',nome_fantasia: 'PCRJ',cnpj: '73214439000190',regional: 'Governo',sap: '')
Empresa.create!(razao: 'PREFEITURA DE SANTA VITÓRIA DO PALMAR',nome_fantasia: 'PREFEITURA DE SANTA VITÓRIA DO PALMAR',cnpj: '88824099000197',regional: 'Governo',sap: '')
Empresa.create!(razao: 'PREFEITURA MUNICIPAL DE ANÁPOLIS',nome_fantasia: 'PMA - ANÁPOLIS',cnpj: '01067479000146',regional: 'Governo',sap: '')
Empresa.create!(razao: 'PREFEITURA MUNICIPAL DE APARECIDA DE GOIÂNIA',nome_fantasia: 'PMAG',cnpj: '01005727000124',regional: 'Governo',sap: '')
Empresa.create!(razao: 'PREFEITURA MUNICIPAL DE COLOMBIA',nome_fantasia: 'PREFEITURA DE COLOMBIA',cnpj: '52381720000148',regional: 'Governo',sap: '')
Empresa.create!(razao: 'PREFEITURA MUNICIPAL DE LUIS EDUARDO MAGALHÃES',nome_fantasia: 'PREF MUNICIPAL DE LUIS EDUARDO MAGALHÃES',cnpj: '04214419000105',regional: 'Governo',sap: '')
Empresa.create!(razao: 'PREFEITURA MUNICIPAL DE SANTANA DO LIVRAMENTO',nome_fantasia: 'PREFEITURA MUNICIPAL DE SANTANA DO LIVRAMENTO',cnpj: '88124961000159',regional: 'Governo',sap: '')
Empresa.create!(razao: 'PREFEITURA MUNICIPAL DO SANTO ANTÔNIO DE  POSSI',nome_fantasia: 'PMSAD',cnpj: '00097857000171',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'PREMIER SOLUÇÕES EIRELI',nome_fantasia: 'PREMIER SOLUÇÕES',cnpj: '08380178000117',regional: 'Belém',sap: '')
Empresa.create!(razao: 'PRESIDÊNCIA DA REPÚBLICA',nome_fantasia: 'PRESIDÊNCIA DA REPÚBLICA',cnpj: '00349411000109',regional: 'Governo',sap: '')
Empresa.create!(razao: 'PRIME SYSTEM INFORMATICA LTDA',nome_fantasia: 'PRIME SYSTEM INFORMATICA',cnpj: '12356161000100',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'PROCERGS - CIA PROCESSAMENTO DADOS DO ESTADO RIO GRANDE SUL',nome_fantasia: 'PROCERGS',cnpj: '87124582000104',regional: 'Governo',sap: '')
Empresa.create!(razao: 'PROCESSAMENTO DE DADOS AMAZONAS S.A.',nome_fantasia: 'PRODAM',cnpj: '04407920000180',regional: 'Governo',sap: '')
Empresa.create!(razao: 'PRONTO NET LTDA - EPP',nome_fantasia: 'PRONTO NET',cnpj: '04612766000188',regional: 'Belém',sap: '')
Empresa.create!(razao: 'PROVECOM TELECOMUNICAÇÕES LTDA - ME',nome_fantasia: 'Provecom',cnpj: '07251024000162',regional: 'Belém',sap: '')
Empresa.create!(razao: 'R L GUIMARAES TELECOMUNICACAO - ME',nome_fantasia: 'NETMASTER TELECOMUNICACAO',cnpj: '20975185000167',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'R. M. DE OLIVEIRA INFORMÁTICA LTDA - EPP',nome_fantasia: 'JATIMNET',cnpj: '83857292000100',regional: 'Belém',sap: '')
Empresa.create!(razao: 'R.R.M. SERVIÇOS DE INFORMÁTICA  LTDA - ME',nome_fantasia: 'R.R.M.',cnpj: '07462381000170',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'RÁDIO E TELEVISÃO BANDEIRANTES LTDA.',nome_fantasia: 'TV Bandeirantes - Band',cnpj: '60509239000113',regional: 'São Paulo',sap: '')
Empresa.create!(razao: 'RADIO NETWORK E TELECOM LTDA - ME',nome_fantasia: 'RADIONET TELECOM',cnpj: '20121565000134',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'RC OLIVEIRA ELETRÔNICA E COMUNICAÇÕES LTDA',nome_fantasia: 'ACESSO.COM',cnpj: '01031269000106',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'REDE CONESUL TELECOMUNICAÇÕES LTDA',nome_fantasia: 'REDE CONESUL',cnpj: '08750868000110',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'REDE DE TELECOMUNICACOES CARAJAS EIRELI - EPP',nome_fantasia: 'CARAJASNET',cnpj: '04680405000179',regional: 'Belém',sap: '')
Empresa.create!(razao: 'REDE EXITUS LTDA',nome_fantasia: 'PASSONET',cnpj: '05363299000162',regional: 'Rio de Janeiro',sap: '')
Empresa.create!(razao: 'REDE GLOBO',nome_fantasia: 'Rede Globo Brasília',cnpj: '27865757002571',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'REDE SIVNET TELECOMUNICAÇÕES LTDA',nome_fantasia: 'REDE SIVNET TELECOMUNICAÇÕES LTDA',cnpj: '07781428000168',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'REDE SPEEDNET TELECOM LTDA - ME',nome_fantasia: 'SPEEDNET',cnpj: '12753324000180',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'REDITELECOM ALOFONE TELEFOMUNICAÇÕES LTD',nome_fantasia: 'Reditel Telecom',cnpj: '07734311000123',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'REVO TELECOMUNICACOES LTDA - EPP',nome_fantasia: 'NEXTVIEW TECHNOLOGIES',cnpj: '03680502000107',regional: 'São Paulo',sap: '')
Empresa.create!(razao: 'RICARDO SANTOS DE JESUS & CIA LTDA - ME',nome_fantasia: 'VIVA TELECOM',cnpj: '04985991000160',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'RNP - REDE NACIONAL DE ENSINO E PESQUISA',nome_fantasia: 'RNP',cnpj: '03508097000136',regional: 'Governo',sap: '')
Empresa.create!(razao: 'RODRIGO CASTRO ANDRADE - ME',nome_fantasia: 'RCA NET',cnpj: '09277607000198',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'RODRIGO COSTA MACHADO - SERVIÇOS DE TELEFONIA FIXA COMUTADA - STFC - EIRELI',nome_fantasia: 'CAMAQUÃNET',cnpj: '09389408000171',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'RODRIGO JOSE MARASCA & CIA LTDA - ME',nome_fantasia: 'PRIMATEC TECNOLOGIA',cnpj: '11554260000106',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'RODRIGUES E MACEDO LTDA',nome_fantasia: 'IMPERANET',cnpj: '14788089000107',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'RONDON TELECOM LTDA - ME',nome_fantasia: 'RONDONET TELECOM',cnpj: '09256492000155',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'RONDONTECH TELECOM LTDA - EPP',nome_fantasia: 'RONDONTECH TELECOM',cnpj: '04290584000138',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'RTC INTERNET VIA RÁDIO LTDA',nome_fantasia: 'RURAL TEC',cnpj: '02076048000109',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'SAFEWEB SEGURANÇA DA INFORMAÇÃO LTDA',nome_fantasia: 'SAFEWEB',cnpj: '01579286000174',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'SANNRES TELECOMUNICACOES LTDA - ME',nome_fantasia: 'ASA TELECOM',cnpj: '20062032000129',regional: 'Belém',sap: '')
Empresa.create!(razao: 'SANTINA E ALBERTINA LTDA - ME',nome_fantasia: 'MEGA TURBO',cnpj: '04478833000113',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'SÃO MIGUEL TELECOMUNICAÇÕES E INFORMÁTICA LTDA - ME',nome_fantasia: 'NEVOLI TELECOMUNICAÇÕES',cnpj: '13400311000190',regional: 'Belém',sap: '')
Empresa.create!(razao: 'SBRUSSI E SBRUSSI LTDA - ME',nome_fantasia: 'HELP INTERNET',cnpj: '10947276000135',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'SECRETARIA DE AVIACAO CIVIL',nome_fantasia: 'SAC',cnpj: '13564476000105',regional: 'Governo',sap: '')
Empresa.create!(razao: 'SERPRO',nome_fantasia: 'SERPRO',cnpj: '33683111000107',regional: 'Governo',sap: '')
Empresa.create!(razao: 'SERVIÇO BRASILEIRO DE APOIO ÀS MICRO E PEQUENAS EMPRESAS',nome_fantasia: 'SEBRAE',cnpj: '00330845000145',regional: 'Governo',sap: '')
Empresa.create!(razao: 'SERVIÇOS DE COMUNICAÇÕES LTDA',nome_fantasia: 'MUITO MAIS COMUNICAÇÕES',cnpj: '13546741000114',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'SET SOLUCOES TECNOLOGICAS E INFORMATICA LTDA - ME',nome_fantasia: 'BRIW - BRASIL INTERNET WIRELESS',cnpj: '06119785000100',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'SETE TELECOM LTDA',nome_fantasia: '7CON',cnpj: '10614842000197',regional: 'Belém',sap: '')
Empresa.create!(razao: 'SILMAR ZAMBONI BERTONCELLO',nome_fantasia: 'SILMAR ZAMBONI BERTONCELLO',cnpj: '05829374000138',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'SILVEIRA & ZIQUINATTI LTDA',nome_fantasia: 'CIACOM PROVEDOR DE INTERNET',cnpj: '05121961000178',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'SIM TELECOM LTDA - EPP',nome_fantasia: 'SIM TELECOM',cnpj: '08778322000178',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'SIMONET PROVIDER TELECOMUNICAÇÕES LTDA - ME',nome_fantasia: 'SIMONET PROVIDER',cnpj: '05890739000130',regional: 'Rio de Janeiro',sap: '')
Empresa.create!(razao: 'SINALNET REDES DE COMUNICAÇÕES LTDA - ME',nome_fantasia: 'SINALNET',cnpj: '15361188000170',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'SINERGY NOVAS MÍDIAS LTDA',nome_fantasia: 'SINERGY',cnpj: '03821107000199',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'SKORPION SISTEMA DE TELECOM LTDA',nome_fantasia: 'SKORPIONET',cnpj: '02425327000130',regional: 'Belém',sap: '')
Empresa.create!(razao: 'SKY SERVICOS DE BANDA LARGA LTDA',nome_fantasia: 'SKY',cnpj: '00497373004883',regional: 'São Paulo',sap: '')
Empresa.create!(razao: 'SM NET LTDA ? ME',nome_fantasia: 'SM NET',cnpj: '14359769000105',regional: 'Rio de Janeiro',sap: '')
Empresa.create!(razao: 'SMA NETWORKS INFORMÁTICA LTDA ME',nome_fantasia: 'WEBROUTE INTERNET BANDA LARGA',cnpj: '07787126000168',regional: 'São Paulo',sap: '')
Empresa.create!(razao: 'SOCIEDADE NÚCLEO DE APOIO À PRODUÇÃO E EXPORTAÇÃO DE SOFTWARE DO RIO DE JANEIRO',nome_fantasia: 'RIOSOFT',cnpj: '86846706000194',regional: 'Rio de Janeiro',sap: '')
Empresa.create!(razao: 'SP TELECOMUNICAÇÕES LTDA - ME',nome_fantasia: 'CLICKNET TELECOMUNICAÇÕES',cnpj: '10271457000194',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'SPEED PLANET TELECOMUNICAÇÕES LTDA',nome_fantasia: 'SPEED TELECOM',cnpj: '10505282000132',regional: 'Rio de Janeiro',sap: '')
Empresa.create!(razao: 'SPEEDCONNECT- TECNOLOGIA E EQUIPAMENTOS',nome_fantasia: 'SPEEDCONNECT',cnpj: '10379340000129',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'SPEEDNET LTDA - EPP',nome_fantasia: 'SPEEDNET LTDA',cnpj: '17574884000190',regional: 'Belém',sap: '')
Empresa.create!(razao: 'STAFF COMPUTER LTDA',nome_fantasia: 'CONTILNET',cnpj: '04101555000180',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'STATUS EQUIPAMENTOS DE TELECOMUNICAÇÕES LTDA',nome_fantasia: 'VIA RADIO',cnpj: '01117905000109',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'STONE TECNOLOGIA EIRELI - EPP',nome_fantasia: 'STONE',cnpj: '21099215000181',regional: 'Belém',sap: '')
Empresa.create!(razao: 'SUL AMERICANA TECNOLOGIA E INFORMATICA LTDA',nome_fantasia: 'SOUTHTECH TELECOM',cnpj: '02639055000171',regional: 'São Paulo',sap: '')
Empresa.create!(razao: 'TBN TELECOMUNICAÇÕES LTDA - ME',nome_fantasia: 'TURBONET',cnpj: '24875044000123',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'TCF - TELECOMUNICAÇÕES CAMPO FLORIDO LTDA',nome_fantasia: 'TCF - TELECOM',cnpj: '11251678000163',regional: 'Rio de Janeiro',sap: '')
Empresa.create!(razao: 'TCHETURBO PROVEDOR DE INTERNET EIRELI',nome_fantasia: 'TCHETURBO INTERNET PROVIDER',cnpj: '06089278000163',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'TELECOMUNICAÇÕES ALARCÃO E FERNANDES LTDA - ME',nome_fantasia: 'LARCNET',cnpj: '11562559000121',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'TELECOMUNICAÇÕES BRASILEIRAS S. A. - TELEBRAS',nome_fantasia: 'TELEBRAS',cnpj: '00336701000104',regional: 'Governo',sap: '')
Empresa.create!(razao: 'TELECOMUNICAÇÕES NORDESTE LTDA',nome_fantasia: 'TVN',cnpj: '02995233000105',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'TIM CELULAR S.A.',nome_fantasia: 'TIM',cnpj: '04206050000180',regional: 'Rio de Janeiro',sap: '')
Empresa.create!(razao: 'TOLEDO INFORMÁTICA  LTDA',nome_fantasia: 'TOLEDO INFO',cnpj: '09537386000140',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'TOTAL AUTOMAÇÃO COMÉRCIO DE PEÇAS E EQUIPAMENTOS DE INFORMÁTICA LTDA - ME',nome_fantasia: 'TOTAL AUTOMAÇÃO',cnpj: '06850461000130',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'TRÓPICO SISTEMAS E TELECOMUNICAÇÕES DA AMAZÔNIA LTDA',nome_fantasia: 'TRÓPICO',cnpj: '84534254000503',regional: 'Governo',sap: '')
Empresa.create!(razao: 'TUBARON TECNOLOGIAS LTDA - EPP',nome_fantasia: 'TUBARON',cnpj: '07775840000175',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'TURBO NET COMUNICAÇÃO E INFORMÁTICA LTDA',nome_fantasia: 'TURBO NET',cnpj: '04009757000105',regional: 'Belém',sap: '')
Empresa.create!(razao: 'TURBO TELECOM PROVEDOR DE ACESSO A INTERNET LTDA - ME',nome_fantasia: 'VIDEO CLUB',cnpj: '08874991000143',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'TURBONETT TELECOMUNICAÇÕES LTDA - ME',nome_fantasia: 'TURBONETT TELECOMUNICAÇÕES',cnpj: '10918507000182',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'TV OMEGA LTDA',nome_fantasia: 'REDE TV',cnpj: '02131538000160',regional: 'São Paulo',sap: '')
Empresa.create!(razao: 'UNIÃO BRASILEIRA DE EDUCAÇÃO E ASSISTÊNCIA',nome_fantasia: 'PONTIFICIA UNIVERSIDADE CATOLICA DO RS-CAMPUS POA (PUCRS)',cnpj: '88630413000281',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'UNIVERSIDADE FEDERAL DO ESTADO DO RIO DE JANEIRO',nome_fantasia: 'UNI RIO',cnpj: '34023077000107',regional: 'Rio de Janeiro',sap: '')
Empresa.create!(razao: 'V.A. DE PAULA SEGUNDO TELECOMUNICAÇÕES - ME',nome_fantasia: 'DIRECT BANDA LARGA',cnpj: '08921282000114',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'VALDEMAR MELO DA MOTA - ME',nome_fantasia: 'CONECT TELECOM',cnpj: '07353979000120',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'VANTE PROVEDOR DE INTERNET LTDA ME',nome_fantasia: 'Vante Telecom',cnpj: '10201482000100',regional: 'Rio de Janeiro',sap: '')
Empresa.create!(razao: 'VEGAS TELECOM INFORMÁTICA LTDA',nome_fantasia: 'VEGAS TELECOM',cnpj: '10501017000186',regional: 'Rio de Janeiro',sap: '')
Empresa.create!(razao: 'VETORIALNET INFORMATICA E SERVICOS DE INTERNET EIRELI - EPP',nome_fantasia: 'VETORIAL INTERNET',cnpj: '94084266000103',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'VIA SUL TELECOMUNICACOES LTDA - ME',nome_fantasia: 'VIA SUL TELECOM',cnpj: '09254150000104',regional: 'Rio de Janeiro',sap: '')
Empresa.create!(razao: 'VIACOM NEXT GENERATION COMUNICAÇÃO LTDA - EPP ',nome_fantasia: 'IZOOM',cnpj: '06172384000106',regional: 'Belém',sap: '')
Empresa.create!(razao: 'VIGAR PROVEDOR DE ACESSO A INTERNET LTDA',nome_fantasia: 'VIA SUL',cnpj: '13083648000110',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'VIRTUALCITY COMERCIO E SERV. DE TELECOM ',nome_fantasia: 'Virtualcity',cnpj: '09214464000175',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'VISADA PROVEDOR DE INTERN LTDA ME',nome_fantasia: 'VISADA PROVEDOR',cnpj: '05555435000205',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'VISION TELECOM E INFORMATICA EIRELI - ME',nome_fantasia: 'VISION TELECOM',cnpj: '18455638000182',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'VITORINO NET LTDA - ME',nome_fantasia: 'VITORINO NET',cnpj: '08415377000113',regional: 'Fortaleza',sap: '')
Empresa.create!(razao: 'VIVA NET LTDA - ME',nome_fantasia: 'VIVA NET',cnpj: '12695351000143',regional: 'São Paulo',sap: '')
Empresa.create!(razao: 'VIVO S.A.',nome_fantasia: 'VIVO',cnpj: '02449992000164',regional: 'São Paulo',sap: '')
Empresa.create!(razao: 'VOCÊ TELECOMUNICAÇÕES LTDA',nome_fantasia: 'VOCÊ TELECOM',cnpj: '07656757000187',regional: 'Belém',sap: '')
Empresa.create!(razao: 'WAVE TELECOM LTDA',nome_fantasia: 'WAVE TELECOM',cnpj: '03847541000148',regional: 'Belém',sap: '')
Empresa.create!(razao: 'WDS TELECOM LTDA - ME',nome_fantasia: 'WDS TELECOM',cnpj: '09356043000189',regional: 'Rio de Janeiro',sap: '')
Empresa.create!(razao: 'WEBMAX TECNOLOGIA LTDA.',nome_fantasia: 'WEBMAX',cnpj: '10651401000165',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'WEDENARDO PEDRO DA COSTA - ME',nome_fantasia: 'NET PREMIUM INFORMATICA',cnpj: '19044970000117',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'WIANET SOLUÇÕES E TECNOLOGIA LTDA',nome_fantasia: 'WIANET',cnpj: '05104611000101',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'WIN TIME INFORMÁTICA LTDA - EPP',nome_fantasia: 'FLEXANET',cnpj: '02391867000140',regional: 'Belém',sap: '')
Empresa.create!(razao: 'WINDTEL SERVICOS',nome_fantasia: 'WINDTEL',cnpj: '19532184000169',regional: 'Belém',sap: '')
Empresa.create!(razao: 'WLAN SISTEMAS LTDA',nome_fantasia: 'WLAN SISTEMAS',cnpj: '14644092000157',regional: 'Belém',sap: '')
Empresa.create!(razao: 'WSP SERVIÇOS DE TELECOMUNICAÇÕES LTDA - ME',nome_fantasia: 'WSP TELECOM',cnpj: '07942413000134',regional: 'Belém',sap: '')
Empresa.create!(razao: 'WWN REDES E COMUNICAÇÕES LTDA - ME',nome_fantasia: 'WWN REDES E COMUNICAÇÕES LTDA - ME',cnpj: '12192411000105',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'YOTTA COMUNICACOES DIGITAIS LTDA - EPP',nome_fantasia: 'YOTTA',cnpj: '13995892000150',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'YZABELLA KRISTINA CALCAGNO ROGRIGUES EIRELI',nome_fantasia: 'LINKFIRE CONSULTORIA EM TI',cnpj: '14122350000135',regional: 'Belém',sap: '')
Empresa.create!(razao: 'ZAP TELECOMUNICAÇÕES LTDA',nome_fantasia: 'ZAP TELECOM',cnpj: '08056021000130',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'ZAPNET PROVEDORES DE INTERNET LTDA',nome_fantasia: 'ZAPNET',cnpj: '05462503000100',regional: 'Brasília',sap: '')
Empresa.create!(razao: 'ZILIONET TELECOMUNICAÇÕES LTDA',nome_fantasia: 'SULNET TELECOMUNICAÇÕES',cnpj: '10220038000123',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'ZONA SUL TELECOM EIRELI - EPP',nome_fantasia: 'ZONA SUL TELECOM EIRELI - EPP',cnpj: '18785251000194',regional: 'Porto Alegre',sap: '')
Empresa.create!(razao: 'ZOTTIS & COSTA TELECOMUNICACOES LTDA',nome_fantasia: 'TELNET WIRELESS',cnpj: '10390703000127',regional: 'Porto Alegre',sap: '')

