
development:
   adapter: mysql2
   encoding: utf8
   reconnect: false
   database: telebras_development
   username: root
   password: bela1010
   host: localhost

test:
   adapter: mysql2
   encoding: utf8
   reconnect: false
   database: telebras_test
   username: root
   password: bela1010
   host: localhost

production:
   adapter: mysql2
   encoding: utf8
   reconnect: false
   database: telebras_production
   username: root
   password: bela1010
   host: localhost
